force-app/main/default/objects/Case/fields/Manager_Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Manager_Response_Date__c</fullName>
    <description>The date a sales manager commented on the case via Chatter</description>
    <inlineHelpText>The date a sales manager commented on the case via Chatter</inlineHelpText>
    <label>Manager Response Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Quality_Assurance.recordType-meta.xml
<RecordType>
    <fullName>Quality_Assurance</fullName>
    <active>true</active>
    <businessProcess>Support</businessProcess>
    <label>Quality Assurance</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Sales.recordType-meta.xml
<RecordType>
    <fullName>Sales</fullName>
    <active>true</active>
    <businessProcess>Sales</businessProcess>
    <label>Sales (BNA)</label>
</RecordType>

force-app/main/default/objects/User/fields/Sales_Team__c.field-meta.xml
<CustomField>
    <fullName>Sales_Team__c</fullName>
    <label>Sales Team</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>BNA Team</fullName>
            </value>
            <value>
                <fullName>Brian Labus</fullName>
            </value>
            <value>
                <fullName>Christopher Sample</fullName>
            </value>
            <value>
                <fullName>Entity Formation Team</fullName>
            </value>
            <value>
                <fullName>Floria Royals</fullName>
            </value>
            <value>
                <fullName>Fulfillment</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Israel Vazquez</fullName>
            </value>
            <value>
                <fullName>Jason Roman</fullName>
            </value>
            <value>
                <fullName>JT Keenan</fullName>
            </value>
            <value>
                <fullName>Keith Marzi</fullName>
            </value>
            <value>
                <fullName>Michael Cashman</fullName>
            </value>
            <value>
                <fullName>Michele Myers</fullName>
            </value>
            <value>
                <fullName>Nesting Team</fullName>
            </value>
            <value>
                <fullName>Training Team</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FeedCommentTriggerHandler.cls
public class FeedCommentTriggerHandler {
    public static void updateCase(List<FeedComment> commentList){
           Profile salesManagerProfile = [SELECT Id FROM Profile WHERE Name = 'Sales Manager'];
           User currentUser = [SELECT Id, Sales_Team__c FROM User WHERE Id = :UserInfo.getUserId()];
           
           //Check if FeedComment was posted by Sales Manager whose Sales team is not null
           if(UserInfo.getProfileId() == salesManagerProfile.Id && currentUser.Sales_Team__c != null){           
           		//make a list of all the parent ids
           		List<Id> caseIds = new List<Id>();
           		for(FeedComment f : commentList){
               		caseIds.add(f.ParentId);
           		}           
               
           		//create a list that will hold cases that fit our criteria
           		List<Case> casesToUpdate = new List<Case>();
                for(Case caseToUpdate : [SELECT Id, Manager_Response_Date__c FROM Case WHERE Id IN :caseIds AND RecordType.DeveloperName ='Quality_Assurance']){
           			//If Case field 'Manager response date' is blank, set it to today.
                	if (caseToUpdate != null && caseToUpdate.Manager_Response_Date__c == null){
                    	caseToUpdate.Manager_Response_Date__c = System.today();
                    	casesToUpdate.add(caseToUpdate);
                	}
           		}
           		update casesToUpdate;
      		}
    }
}