force-app/main/default/objects/Event_Field_Update__c/Event_Field_Update__c.object-meta.xml
<CustomObject>
    <label>Event Field Update</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Update Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Field Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Field_Update__c/fields/Event_History__c.field-meta.xml
<CustomField>
    <fullName>Event_History__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event History</label>
    <referenceTo>Event_History__c</referenceTo>
    <relationshipLabel>Event Field Updates</relationshipLabel>
    <relationshipName>Event_Field_Updates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Field_Update__c/fields/Updated_By__c.field-meta.xml
<CustomField>
    <fullName>Updated_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Updated By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Event_Field_Updates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Field_Update__c/fields/Updated_Field__c.field-meta.xml
<CustomField>
    <fullName>Updated_Field__c</fullName>
    <label>Updated Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_History__c/Event_History__c.object-meta.xml
<CustomObject>
    <description>Psuedo junction object to organize Event Field Updates</description>
    <label>Event History</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Email_Campaign_ID__c.field-meta.xml
<CustomField>
    <fullName>Email_Campaign_ID__c</fullName>
    <label>Email Campaign ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ManagerReassignmentsReportTest.cls
@isTest
public with sharing class ManagerReassignmentsReportTest {
    @isTest
    public static void testGetData(){
        User manager = [SELECT Id FROM User WHERE Profile.Name = 'Sales Manager' AND IsActive = true LIMIT 1];
        List<User> reps = [SELECT Id, Name FROM User WHERE Profile.Name = 'InsideSalesUser - Zuora' AND IsActive = true LIMIT 2];
        Lead l = new Lead(FirstName='first',LastName='last',status='new', company='company', email='test1@gtest.com', OwnerId = manager.Id);
        insert l;
        Event_History__c history = new Event_History__c();
        insert history; 
        Event testEvent = new Event(
            OwnerId = reps[0].Id,
            WhoId = l.Id,
            Subject = 'Test Event',
            StartDateTime = System.now(),
            EndDateTime = System.now().addMinutes(30),
            Email_Campaign_ID__c = '12345',
            Type_of_Appointment__c = 'Tax Savings Analysis',
            Portal_Event_Owner__c = 'Matthew Clark',
            Event_History__c = history.Id,
            Original_Assigned_to__c = reps[0].Id
        );
        insert testEvent;

        Event_Field_Update__c up = new Event_Field_Update__c(
            Updated_Field__c = 'Assigned To',
            Old_Value__c = reps[0].Name,
            New_Value__c = reps[1].Name,
            Event_History__c = history.Id,
            Updated_By__c = manager.Id
        );
        insert up;

        ManagerReassignmentsReport.getData();
    } 
}