force-app/main/default/objects/Event_Field_Update__c/Event_Field_Update__c.object-meta.xml
<CustomObject>
    <label>Event Field Update</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Update Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Field Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Field_Update__c/fields/Event_History__c.field-meta.xml
<CustomField>
    <fullName>Event_History__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event History</label>
    <referenceTo>Event_History__c</referenceTo>
    <relationshipLabel>Event Field Updates</relationshipLabel>
    <relationshipName>Event_Field_Updates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_History__c/Event_History__c.object-meta.xml
<CustomObject>
    <description>Psuedo junction object to organize Event Field Updates</description>
    <label>Event History</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InsertFieldUpdateQueueable.cls
//Matt Clark - 12/2/22
//Simple queueable class to create records for Event field update tracking

public without sharing class InsertFieldUpdateQueueable implements Queueable{
    private Map<Event_Field_Update__c, Event> updates;
    
    public InsertFieldUpdateQueueable(Map<Event_Field_Update__c, Event> fieldUpdates){
        this.updates = fieldUpdates;
    }
    
    public void execute(System.QueueableContext qc){
        System.debug('Starting insertFieldUpdate()');        
        Map<Event_Field_Update__c, Event> fieldUpdates = this.updates;
        System.debug(fieldUpdates);
        List<Event> eventsToUpdate = new List<Event>();
        for(Event updatedEvent : new Set<Event>(fieldUpdates.values())){
            if(updatedEvent.Event_History__c == null){
                Event_History__c history = new Event_History__c();
                insert history;
                System.debug('history: '+history);
                //updatedEvent.Event_History__c = history.Id;
                eventsToUpdate.add(new Event(Id = updatedEvent.Id, Event_History__c = history.Id));
               }
        }
        if(!eventsToUpdate.isEmpty()){
            System.debug('eventsToUpdate: '+eventsToUpdate);
            update eventsToUpdate;
        }
        Map<Id, Event> eventsToUpdateMap = new Map<Id, Event>(eventsToUpdate);
        for(Event_Field_Update__c fieldUpdate : fieldUpdates.keySet()){
            Event updatedEvent = fieldUpdates.get(fieldUpdate);
            if(updatedEvent.Event_History__c == null){
                fieldUpdate.Event_History__c = 
                eventsToUpdateMap.get(updatedEvent.Id)
                .Event_History__c;
            } else {
                fieldUpdate.Event_History__c = updatedEvent.Event_History__c;
            }
            System.debug('fieldUpdate: '+fieldUpdate);
        }
        insert new List<Event_Field_Update__c>(fieldUpdates.keySet());
    }


}