force-app/main/default/objects/NoteDispatcher__c/NoteDispatcher__c.object-meta.xml
<CustomObject>
    <description>Will trigger outbound message for Notes object</description>
    <label>NoteDispatcher</label>
    <nameField>
        <label>NoteDispatcher Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NoteDispatcher</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NoteDispatcher__c/fields/NoteID__c.field-meta.xml
<CustomField>
    <fullName>NoteID__c</fullName>
    <description>Original SF Note ID</description>
    <label>NoteID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestNoteCreateUpdate.cls
@IsTest
private class TestNoteCreateUpdate
{
    @IsTest
    static void testCreateNote()
    {
    	Account acc= new Account(Name = 'Acme');
        Test.startTest();        
    	insert acc;        
    	Note nte = new Note(Title = 'Test', ParentId = acc.Id);
        insert nte;
        Test.stopTest();

        NoteDispatcher__c disp = [SELECT Id, NoteID__c  FROM NoteDispatcher__c WHERE NoteID__c = :nte.Id];
    }
}