force-app/main/default/objects/Active_Subscription_Line__c/Active_Subscription_Line__c.object-meta.xml
<CustomObject>
    <label>Active Subscription Line</label>
    <nameField>
        <label>Active Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Active_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription__c</fullName>
    <label>Active Subscription</label>
    <referenceTo>Active_Subscriptions__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/Active_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Active Subscription</label>
    <nameField>
        <label>Active Subscriptions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscriptions__c/fields/Cancelled_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancelled_Date__c</fullName>
    <label>Cancelled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/Subscription_Status__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Status__c</fullName>
    <label>Subscription Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/ChargeOver_Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription Line Item</label>
    <nameField>
        <label>ChargeOver Subscription Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Active_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Active Subscription</label>
    <referenceTo>Active_Subscriptions__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Active_Subscription_Line__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Subscription Line</label>
    <referenceTo>Active_Subscription_Line__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Historical_Update__c.field-meta.xml
<CustomField>
    <fullName>Historical_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to trigger mass updates.</description>
    <label>Historical Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChargeOverBatchSubExptnCheck.cls
/**
 * Created by Samuel Reyes on 3/23/2021.
 */

global with sharing class ChargeOverBatchSubExptnCheck implements Database.Batchable<SObject>, Schedulable
{
    global void execute(SchedulableContext context)
    {
        ChargeOverBatchSubExptnCheck ndb = new ChargeOverBatchSubExptnCheck();
        String cronStrHour = '0 0 * * * ?';
        String jobName = 'ActiveStatusExpirationCheck_Daily';

        //Schedule the next job for next day.
        try
        {
            System.schedule(jobName, cronStrHour, ndb);
            System.debug('ActiveStatusExpirationCheck_Daily scheduled....');
        } catch (Exception e)
        {
            System.debug('ActiveStatusExpirationCheck_Daily job already scheduled :: ' + e);
        }

        //Run actual batch job for this run.
        Database.executeBatch(ndb);
    }

    global Database.QueryLocator start(Database.BatchableContext context)
    {
        //Instantiating these dates in each method to avoid query limits.
        Date today = Date.today();
        return Database.getQueryLocator([SELECT Id, Expiration_Date__c, Subscription_Status__c, Cancelled_Date__c FROM Active_Subscriptions__c
        WHERE (Expiration_Date__c <= :today OR Expiration_Date__c = NULL)
        AND Cancelled_Date__c != NULL
        AND Subscription_Status__c IN ('Paused','Active','Active - Pending Cancel')]);
    }

    global void execute(Database.BatchableContext context, List<Active_Subscriptions__c> scope)
    {
        Date today = Date.today();

        Set<Id> sliIds = new Set<Id>();
        Set<Id> activeSubIds = new Set<Id>();
        for(Active_Subscriptions__c sub : scope)
        {
            if(null != sub.Cancelled_Date__c && (sub.Expiration_Date__c < sub.Cancelled_Date__c || sub.Cancelled_Date__c < Date.today() && null == sub.Expiration_Date__c))
            {
                activeSubIds.add(sub.Id);
            }
        }

        if(!activeSubIds.isEmpty())
        {
            ChargeOver_Subscription_Line_Item__c[] sliToTriggerUpdate = new ChargeOver_Subscription_Line_Item__c[0];
            for(Active_Subscription_Line__c line : [SELECT Id, ChargeOver_Subscription_Line_Item__c, ChargeOver_Subscription_Line_Item__r.Historical_Update__c,
                    Expiration_Date__c, Cancelled_Date__c
                FROM Active_Subscription_Line__c WHERE Active_Subscription__c IN :activeSubIds])
            {
                if(!sliIds.contains(line.ChargeOver_Subscription_Line_Item__c) && (line.Expiration_Date__c > line.Cancelled_Date__c || line.Expiration_Date__c < today || null == line.Expiration_Date__c))
                {
                    sliIds.add(line.ChargeOver_Subscription_Line_Item__c);
                    sliToTriggerUpdate.add(new ChargeOver_Subscription_Line_Item__c(Id=line.ChargeOver_Subscription_Line_Item__c,
                            Historical_Update__c=(line.ChargeOver_Subscription_Line_Item__r.Historical_Update__c) ? false : true));
                }
            }

            //Switch the historical update field on the records to force a status recalculation.
            if(!sliToTriggerUpdate.isEmpty())
            {
                update sliToTriggerUpdate;
            }
        }

    }

    global void finish(Database.BatchableContext context){}

}