force-app/main/default/objects/Active_Subscription_Line__c/Active_Subscription_Line__c.object-meta.xml
<CustomObject>
    <label>Active Subscription Line</label>
    <nameField>
        <label>Active Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Active_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription__c</fullName>
    <label>Active Subscription</label>
    <referenceTo>Active_Subscriptions__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Applied_Account__c.field-meta.xml
<CustomField>
    <fullName>Applied_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account that the Active Subscription Line is related to. This determines entitlements within the portal</description>
    <label>Applied Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscription Lines (Applied Account)</relationshipLabel>
    <relationshipName>Active_Subscription_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Created_by_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Created_by_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate if the ASL was created by a renwal invoice</description>
    <inlineHelpText>Checkbox to indicate if the ASL was created by a renwal invoice</inlineHelpText>
    <label>Created by Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Subscription_Amount__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Amount__c</fullName>
    <label>Subscription Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <description>Used to relate to a specific Active Subscription.</description>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/Active_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Active Subscription</label>
    <nameField>
        <label>Active Subscriptions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscriptions__c/fields/Subscription_Amount__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Amount__c</fullName>
    <label>Subscription Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/Total_Applied__c.field-meta.xml
<CustomField>
    <fullName>Total_Applied__c</fullName>
    <label>Total Applied</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/Total_Purchased__c.field-meta.xml
<CustomField>
    <fullName>Total_Purchased__c</fullName>
    <label>Total Purchased</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/Unique_Identifier__c.field-meta.xml
<CustomField>
    <fullName>Unique_Identifier__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Unique Identifier</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ChargeOver_ActiveSubTriggerHandler.cls
public with sharing class ChargeOver_ActiveSubTriggerHandler
{
    public static void doBeforeTrigger(Active_Subscriptions__c[] triggerNew, Map<Id, Active_Subscriptions__c> oldMap, Boolean isInsert, Boolean isUpdate)
    {
        if(isUpdate){ updateTotalQuantity(triggerNew); }
    }

    public static void doAfterTrigger(Active_Subscriptions__c[] triggerNew, Map<Id, Active_Subscriptions__c> newMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete)
    {
        if(isInsert)
        {
        }

    }

    public static void updateTotalQuantity(Active_Subscriptions__c[] triggerNew)
    {
        System.debug(LoggingLevel.FINER, 'updateTotalQuantity trigger entered :: ' + triggerNew);
        Set<Id> idsToQuery = new Set<Id>();
        for(Active_Subscriptions__c sub : triggerNew)
        {
            idsToQuery.add(sub.Id);
        }

        System.debug(LoggingLevel.FINE, 'idsToQuery :: ' + idsToQuery);
        Map<String,Decimal> counter = new Map<String,Decimal>();
        Map<String,Decimal> prices = new Map<String, Decimal>();
        Map<String,Decimal> applied = new Map<String, Decimal>();
        Active_Subscription_Line__c[] lines = new Active_Subscription_Line__c[0];
        for(Active_Subscription_Line__c line : [SELECT Id, Unique_Identifier__c, Created_by_Renewal__c, Subscription_Amount__c, Applied_Account__c FROM Active_Subscription_Line__c WHERE Active_Subscription__c IN: idsToQuery])
        {
            lines.add(line);

            //Count number of ASL records with specific unique identifier. This is based on the primary account.
            if(null != line.Unique_Identifier__c && counter.keySet().contains(line.Unique_Identifier__c))
            {
                Decimal currentCount = counter.get(line.Unique_Identifier__c);
                currentCount = currentCount + 1;
                counter.put(line.Unique_Identifier__c, currentCount);
            } else{ counter.put(line.Unique_Identifier__c, 1); }

            if(line.Created_by_Renewal__c){
                //SUM the amount for each related ASL and then put the total in the map.
                if(null != line.Subscription_Amount__c && prices.containsKey(line.Unique_Identifier__c))
                {
                    Decimal totalPriceSum = prices.get(line.Unique_Identifier__c);
                    totalPriceSum = totalPriceSum + line.Subscription_Amount__c;
                    prices.put(line.Unique_Identifier__c, totalPriceSum);
                } else{ prices.put(line.Unique_Identifier__c, (null == line.Subscription_Amount__c) ? 0 : line.Subscription_Amount__c); }
            }
            
            //Count the number of records that have had an account applied to them. Only count active ones towards total applied.
            if(null != line.Unique_Identifier__c && applied.containsKey(line.Unique_Identifier__c))
            {
	            System.debug('check line value :: ' + line);
                Decimal totalApplied = applied.get(line.Unique_Identifier__c);
                totalApplied = (null != line.Applied_Account__c) ? totalApplied  + 1 : totalApplied + 0;
//	            totalApplied = totalApplied + 1;
                applied.put(line.Unique_Identifier__c, totalApplied);
            }
            else
            {
	            Decimal startValue = (null != line.Applied_Account__c) ? 1 : 0;
	            applied.put(line.Unique_Identifier__c, startValue);
            }
        }

        System.debug(LoggingLevel.FINE, 'counterMap :: ' + counter);

        for(Active_Subscriptions__c sub : triggerNew)
        {
            if(counter.keySet().contains(sub.Unique_Identifier__c))
            {
                Decimal currentCount = counter.get(sub.Unique_Identifier__c);
                sub.Total_Purchased__c = currentCount;
            }

            if(prices.keySet().contains(sub.Unique_Identifier__c))
            {
                Decimal totalPrice = prices.get(sub.Unique_Identifier__c);
                sub.Subscription_Amount__c = totalPrice;
            }

            if(applied.keySet().contains(sub.Unique_Identifier__c))
            {
                Decimal totalApplied = applied.get(sub.Unique_Identifier__c);
                sub.Total_Applied__c = totalApplied;
            }
        }

    }
}