force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/ChargeOver_Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription Line Item</label>
    <nameField>
        <label>ChargeOver Subscription Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Cancel_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date_Time__c</fullName>
    <label>Cancel Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Historical_Update__c.field-meta.xml
<CustomField>
    <fullName>Historical_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to trigger mass updates.</description>
    <label>Historical Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_End_Date__c</fullName>
    <description>The Service End Date of the most recent invoice line item</description>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MarkHistoricalUpdate.cls
public class MarkHistoricalUpdate implements Database.Batchable<sObject>, Schedulable {
    public String batchQuery = 
          'SELECT Id, Name, Service_End_Date__c, Cancel_Date_Time__c '
        + 'FROM ChargeOver_Subscription_Line_Item__c '
        + 'WHERE Service_End_Date__c < TODAY '
        + 'AND Cancel_Date_Time__c != null '
        + 'AND Status__c IN (\'Active\', \'Paused\', \'Active - Pending Cancel\', \'Suspended\')';

    public MarkHistoricalUpdate() {}
    public Database.QueryLocator start(Database.BatchableContext bc)  {
        return Database.getQueryLocator(batchQuery);
    }
    public void execute(SchedulableContext context) {
        MarkHistoricalUpdate markUpdate = new MarkHistoricalUpdate();
        Database.executeBatch(markUpdate, 200);
    }
    public void execute(Database.BatchableContext bc, List<ChargeOver_Subscription_Line_Item__c> coSubLines){
        this.execute(coSubLines);
    }
    public void execute(List<ChargeOver_Subscription_Line_Item__c> coSubLines) {
        List<ChargeOver_Subscription_Line_Item__c> toUpdateCoSubLines = new List<ChargeOver_Subscription_Line_Item__c>();
        for(ChargeOver_Subscription_Line_Item__c subscriptionLine : coSubLines){
            subscriptionLine.Historical_Update__c = true;
            toUpdateCoSubLines.add(subscriptionLine);
        }
        update toUpdateCoSubLines;
        
    }

    public void finish(Database.BatchableContext bc){}    
}