force-app/main/default/objects/Product2/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ChargeOver__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ChargeOver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Environment__c.field-meta.xml
<CustomField>
    <fullName>Environment__c</fullName>
    <label>Environment</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>ClientBooks</fullName>
            </value>
            <value>
                <fullName>Sprout</fullName>
            </value>
            <value>
                <fullName>Vendasta</fullName>
            </value>
            <value>
                <fullName>EIN Tax Filing</fullName>
            </value>
            <value>
                <fullName>Entity Formation</fullName>
            </value>
            <value>
                <fullName>EIN Partner</fullName>
                <isActive>false</isActive>
                <label>EIN Partner</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/HTML_Description__c.field-meta.xml
<CustomField>
    <fullName>HTML_Description__c</fullName>
    <label>HTML Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/No_Split_Allowed__c.field-meta.xml
<CustomField>
    <fullName>No_Split_Allowed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No Split Allowed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>This field indicates what order the product will appear on a ChargeOver invoice. If 1, then all of the other product descriptions will display on a single product, if 2 or greater that will affect the other sort orders.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GuidedSellingProductLineControllerTest.cls
@IsTest
public with sharing class GuidedSellingProductLineControllerTest {
    @IsTest static void mainTest() {
        Product2 p = new Product2(Name = 'Loan Agreement', IsActive=true, Guided_Selling_Identifier__c='Personal Return',
        ChargeOver__c = true, Environment__c='Standard',Billing_Frequency__c = 'Annual',HTML_Description__c = 'test', Description = 'test', No_Split_Allowed__c = true, sort_Order__c = 2);
        insert p;

        GuidedSellingProductLineController cont = new GuidedSellingProductLineController();
        cont.productValue = new GuidedSellingProduct(p);
        cont.setUnitPrice(cont.getUnitPrice());
        cont.setProdSubtotal(cont.getProdSubtotal());

        cont.productValue.adjustedPrice = null;
        cont.productValue.subtotal = 123;
        cont.setUnitPrice(cont.getUnitPrice());
        cont.setProdSubtotal(cont.getProdSubtotal());
        
        cont.setdisableQuantity(cont.getdisableQuantity());
        cont.setdisplayRow(cont.getdisplayRow());
        
        
    }
}