force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/Active_Subscription_Line__c.object-meta.xml
<CustomObject>
    <label>Active Subscription Line</label>
    <nameField>
        <label>Active Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Active_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription__c</fullName>
    <label>Active Subscription</label>
    <referenceTo>Active_Subscriptions__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/ChargeOver_Subscription__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription</label>
    <referenceTo>ChargeOver_Subscription__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/Active_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Active Subscription</label>
    <nameField>
        <label>Active Subscriptions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscriptions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscriptions</relationshipLabel>
    <relationshipName>Active_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/ChargeOver_Subscription__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription</label>
    <referenceTo>ChargeOver_Subscription__c</referenceTo>
    <relationshipLabel>Active Subscriptions</relationshipLabel>
    <relationshipName>Active_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Active Subscriptions</relationshipLabel>
    <relationshipName>Active_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/SOW_Description__c.field-meta.xml
<CustomField>
    <fullName>SOW_Description__c</fullName>
    <label>SOW Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/ChargeOver_Subscription__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription</label>
    <nameField>
        <label>ChargeOver Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscriptions</relationshipLabel>
    <relationshipName>ChargeOver_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Active_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Denotes which Active Subscription this record is being aggregated into.</description>
    <label>Active Subscription</label>
    <referenceTo>Active_Subscriptions__c</referenceTo>
    <relationshipLabel>ChargeOver Subscriptions</relationshipLabel>
    <relationshipName>ChargeOver_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_End_Date__c</fullName>
    <description>The Date a client&apos;s service ends based on their most recent invoice.</description>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled due to non-payment</fullName>
            </value>
            <value>
                <fullName>Cancelled manually</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Trial Period Over</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>The date the ChargeOver subscription was created.</description>
    <label>Subscription Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/ChargeOver_Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription Line Item</label>
    <nameField>
        <label>ChargeOver Subscription Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Cancel_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Cancel_Date_Time__c</fullName>
    <label>Cancel Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription</label>
    <referenceTo>ChargeOver_Subscription__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Historical_Update__c.field-meta.xml
<CustomField>
    <fullName>Historical_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to trigger mass updates.</description>
    <label>Historical Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Service_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Service_End_Date__c</fullName>
    <description>The Service End Date of the most recent invoice line item</description>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <label>Subscription Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <formula>Text (Account.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SOW_Description__c.field-meta.xml
<CustomField>
    <fullName>SOW_Description__c</fullName>
    <label>SOW Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ZZ_Primary_Category__c.field-meta.xml
<CustomField>
    <fullName>ZZ_Primary_Category__c</fullName>
    <description>Business, Personal, or business and personal</description>
    <label>ZZ Primary Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChargeOverBatchSubExptnCheckTest.cls
@IsTest
private class ChargeOverBatchSubExptnCheckTest
{
    @TestSetup
    private static void testSetup()
    {
        Account pAccount = new Account(Name = 'Personal', Business_Account__c = false);
        insert pAccount;

        Contact cont = new Contact(AccountId = pAccount.Id, LastName = 'Pho', FirstName = 'Soup');
        insert cont;

        Product2 prod = new Product2(Name = 'TestProduct', Standard_Price__c = 1.0, Description = 'Test', Family = 'Bookkeeping', SOW_Description__c = 'Test', ZZ_Primary_Category__c = 'Business');
        insert prod;

        Date today = Date.today();

        ChargeOver_Subscription__c sliSub = new ChargeOver_Subscription__c(Name = 'Test', Account__c = pAccount.Id, Subscription_Start_Date__c = Datetime.now(), Service_End_Date__c = today.addDays(10), Status__c = 'Active');
        insert sliSub;

        ChargeOver_Subscription_Line_Item__c sli = new ChargeOver_Subscription_Line_Item__c(ChargeOver_Subscription__c = sliSub.Id, Quantity__c = 2, Account__c = pAccount.Id, Cancel_Date_Time__c = today.addDays(2),
        Product__c = prod.Id, Status__c = 'Active', Price_Per_Unit__c = 10.0, Historical_Update__c = false, Subscription_Start_Date__c = Datetime.now());
        insert sli;

        System.debug('Sub :: ' + sliSub);
        ChargeOver_Subscription__c hasDate = [SELECT Subscription_Start_Date__c FROM ChargeOver_Subscription__c WHERE Subscription_Start_Date__c != NULL LIMIT 1];
        System.debug('hasDate :: ' + hasDate);
        System.debug('ASL should exist :: ' + [SELECT Id, Status__c, Active_Subscription__c, ChargeOver_Subscription_Line_Item__c, ChargeOver_Subscription__r.Subscription_Start_Date__c, Start_Date__c FROM Active_Subscription_Line__c WHERE Start_Date__c != NULL]);

        Account nAccount = new Account(Name = 'Business', Business_Account__c = true);
        insert nAccount;

    }

    @IsTest
    static void testBatchClass()
    {
        Date deadDate = Date.today().addDays(-10);
        Active_Subscription_Line__c line = [SELECT Id, Active_Subscription__r.Subscription_Status__c, Active_Subscription__c, ChargeOver_Subscription_Line_Item__c, ChargeOver_Subscription_Line_Item__r.ChargeOver_Subscription__c FROM Active_Subscription_Line__c LIMIT 1];
        System.debug('active sub status :: ' + line.Active_Subscription__r.Subscription_Status__c);
        line.Expiration_Date__c = deadDate;
        update line;

        Active_Subscriptions__c aSub = [SELECT Id FROM Active_Subscriptions__c WHERE Id =: line.Active_Subscription__c LIMIT 1];
        aSub.Cancelled_Date__c = deadDate;
        aSub.Expiration_Date__c = deadDate.addDays(-1);
        update aSub;

        ChargeOver_Subscription__c sub = [SELECT Id FROM ChargeOver_Subscription__c WHERE Id = : line.ChargeOver_Subscription_Line_Item__r.ChargeOver_Subscription__c LIMIT 1];
        sub.Service_End_Date__c = Date.today().addDays(-100);
        sub.Cancellation_Date__c = Date.today().addDays(-10);
        update sub;

        Test.startTest();
        ChargeOverBatchSubExptnCheck job = new ChargeOverBatchSubExptnCheck();
        job.execute(null);
        Test.stopTest();

        Active_Subscription_Line__c line_updated = [SELECT Id, Active_Subscription__r.Subscription_Status__c FROM Active_Subscription_Line__c WHERE Id =: line.Id LIMIT 1];
//        System.assertEquals(true, line_updated.Active_Subscription__r.Subscription_Status__c.containsIgnoreCase('Cancelled'),'Actual status :: ' + line_updated.Active_Subscription__r.Subscription_Status__c);
        System.assertNotEquals(null,line_updated.Active_Subscription__r.Subscription_Status__c);
    }
}