force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>1st Year Client</fullName>
            </value>
            <value>
                <fullName>Renewed Client</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Active-Pending Cancel (Pause)</fullName>
            </value>
            <value>
                <fullName>Paused Client</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ChargeOver_Initial_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Initial_Payment_Date__c</fullName>
    <description>The Transaction Date of the earliest ChargeOver Transaction related to the Account</description>
    <label>ChargeOver Initial Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChargeOver_Most_Recent_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Most_Recent_Payment_Date__c</fullName>
    <description>The Transaction Date of the most recent ChargeOver Payment Transaction related to the Account</description>
    <label>ChargeOver Most Recent Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Status__c.field-meta.xml
<CustomField>
    <fullName>Finance_Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Account_Status__c</fullName>
    <label>Last Account Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/ChargeOver_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Invoice Line Item</label>
    <nameField>
        <label>ChargeOver Invoice Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Invoice Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/ChargeOver_Invoice__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Invoice__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Invoice</label>
    <referenceTo>ChargeOver_Invoice__c</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Number_of_Recurs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Recurs__c</fullName>
    <label># of times this has recurred</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/ChargeOver_Subscription__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription</label>
    <nameField>
        <label>ChargeOver Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscriptions</relationshipLabel>
    <relationshipName>ChargeOver_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Converted_From_Subscription__c.field-meta.xml
<CustomField>
    <fullName>Converted_From_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The subscription used as the source for this new subscription</description>
    <label>Converted From Subscription</label>
    <referenceTo>ChargeOver_Subscription__c</referenceTo>
    <relationshipLabel>ChargeOver Subscriptions</relationshipLabel>
    <relationshipName>ChargeOver_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Initial_Refund_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Initial_Refund_Percentage__c</fullName>
    <description>The percentage of a ChargeOver Subscription where the related subscription and invoice lines have a Payment Type of Initial that has been refunded out of the total amount paid.</description>
    <formula>IF( AND( NOT(ISBLANK( Cancellation_Date__c )), Total_Initial_Paid_Amount__c = 0 ),
1,
((-1* Total_Initial_Refund_Amount__c )/ Total_Initial_Paid_Amount__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Initial Refund Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Sale_Completed_By_Detail__c.field-meta.xml
<CustomField>
    <fullName>Sale_Completed_By_Detail__c</fullName>
    <description>The details of the Sale Completed By field, which may contain any specific website name, partner, or other source</description>
    <label>Sale Completed By Detail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled due to non-payment</fullName>
            </value>
            <value>
                <fullName>Cancelled manually</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Trial Period Over</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/ChargeOver_Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription Line Item</label>
    <nameField>
        <label>ChargeOver Subscription Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Initial_Refund_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Initial_Refund_Percentage__c</fullName>
    <description>The percentage of a ChargeOver Subscription line where the related invoice line has a Payment Type of Initial that has been refunded out of the total amount paid.</description>
    <formula>IF( AND( NOT(ISBLANK(Cancel_Date_Time__c)), Total_Initial_Paid_Amount__c = 0 ),
1,
((-1* Total_Initial_Refund_Amount__c )/ Total_Initial_Paid_Amount__c )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Initial Refund Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Total_Initial_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Initial_Paid_Amount__c</fullName>
    <description>The total amount paid for all related invoice lines of the ChargeOver Subscription where the Payment Type is Initial</description>
    <label>Total Initial Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Calculator_Location__c.field-meta.xml
<CustomField>
    <fullName>Calculator_Location__c</fullName>
    <description>Used to indicate if the product should be included in the pricing calculator. Field values indicate what type of product it&apos;s connected with for dynamic pricing purposes.</description>
    <label>Calculator Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advisory</fullName>
            </value>
            <value>
                <fullName>A La Carte</fullName>
            </value>
            <value>
                <fullName>Back Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Back Business Return</fullName>
            </value>
            <value>
                <fullName>Back Personal Return</fullName>
            </value>
            <value>
                <fullName>Back Quarterly Payroll</fullName>
            </value>
            <value>
                <fullName>Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Business Return</fullName>
            </value>
            <value>
                <fullName>Corp State Filing</fullName>
            </value>
            <value>
                <fullName>Foreign State</fullName>
            </value>
            <value>
                <fullName>LLC State Filing</fullName>
            </value>
            <value>
                <fullName>Non-Profit Back Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Non-Profit Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Personal Return</fullName>
            </value>
            <value>
                <fullName>State Filing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ChargeOver__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ChargeOver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountStatusHandler.cls
public class AccountStatusHandler {

    public static void assignAccountStatus(List<Id> accountIds){
        Id portalProductId;
        if(!Test.isRunningTest()){
            portalProductId = [ SELECT Id, Name FROM Product2 WHERE ChargeOver__c = true AND Calculator_Location__c = 'A La Carte' AND Name = '1-800Accountant Access' LIMIT 1].Id;
        }
        Map<Id, Account> mappedAccounts = new Map<Id, Account>([
            SELECT Id, Name, Account_Status__c, ChargeOver_Most_Recent_Payment_Date__c, Finance_Status__c,
            ChargeOver_Initial_Payment_Date__c, Last_Account_Status__c,
                (SELECT Id, Name, Initial_Refund_Percentage__c, Status__c, Total_Initial_Paid_Amount__c
                    FROM ChargeOver_Subscriptions__r
                    WHERE (NOT Sale_Completed_By_Detail__c LIKE '%1099issuer%')
                ),
                (SELECT Id, Name, Number_of_Recurs__c, Product__c
                    FROM ChargeOver_Invoice_Line_Items__r
                    WHERE ChargeOver_Invoice__r.ChargeOver_Invoice_Status__c != 'Void'
                    AND (Payment_Type__c = 'Renewal'
                    OR (Payment_Type__c = 'Recurring'
                    AND Number_of_Recurs__c > 12
                    AND Product__c != :portalProductId)
                    )
                )
            FROM Account
            WHERE Id IN :accountIds
        ]);

        Map<Id, ChargeOver_Subscription__c> mappedSubscriptions = new Map<Id, ChargeOver_Subscription__c>([
            SELECT Id, Name, Status__c, Account__c, Initial_Refund_Percentage__c,
            (
                SELECT Id, Name, ChargeOver_Subscription__c, Account__c, ChargeOver_Invoice_Status__c, Invoice_Date__c
                FROM ChargeOver_Invoices__r
            ),
            (
                SELECT Id, Name, Status__c
                FROM ChargeOver_Subscription_Line_Items__r
                WHERE Status__c = 'Active - Pending Cancel'
            )
            FROM ChargeOver_Subscription__c
            WHERE Account__c IN :accountIds
        ]);

        // Map<Id, ChargeOver_Subscription__c> mappedActiveSubscriptions = new Map<Id, ChargeOver_Subscription__c>([
        //     SELECT Id, Name, Status__c, Account__c, Initial_Refund_Percentage__c,
        //     (
        //         SELECT Id, Name, ChargeOver_Subscription__c, Account__c, ChargeOver_Invoice_Status__c, Invoice_Date__c
        //         FROM ChargeOver_Invoices__r
        //     ),
        //     (
        //         SELECT Id, Name, Status__c
        //         FROM ChargeOver_Subscription_Line_Items__r
        //         WHERE Status__c = 'Active'
        //     )
        //     FROM ChargeOver_Subscription__c
        //     WHERE Account__c IN :accountIds
        // ]);

        Map<Id, Account> toUpdateAccounts = new Map<Id, Account>();
        for(Account a : mappedAccounts.values()){
            //Tracking attributes
            Boolean refunded = false;
            Boolean hasPending = false;
            Boolean allCancelled = true;
            Boolean allSuspended = true;
            //Status Booleans set to true when the conditions for the status is met
            Boolean current = false;
            Boolean dormant = false;
            Boolean pastDue = false;
            Boolean firstYear = false;
            Boolean renewed = false;
            Boolean pendingCancel = false;
            Boolean partnerSubscribed = false;
            for(ChargeOver_Subscription__c cos : a.ChargeOver_Subscriptions__r){
                //Tracking if they were refunded or not
                if(cos.Initial_Refund_Percentage__c > 30
                && cos.Total_Initial_Paid_Amount__c > 0){
                    refunded = true;
                }
                if(!mappedSubscriptions.get(cos.Id).ChargeOver_Subscription_Line_Items__r.isEmpty()
                && a.ChargeOver_Initial_Payment_Date__c != null){ //updated criteria -mc
                    pendingCancel = true;
                }
                //if(!mappedActiveSubscriptions.get(cos.Id).ChargeOver_Subscription_Line_Items__r.isEmpty()
                if(cos.Status__c == 'Current'
                && a.ChargeOver_Initial_Payment_Date__c == null){ //added new status -mc
                    partnerSubscribed = true;
                }
                //Tracking if all the statuses are cancelled
                if(null != cos.Status__c && !cos.Status__c.contains('Cancelled')){
                    allCancelled = false; 
                    //If they've got a current subscription the invoices need to be checked 
                    if('Current' == cos.Status__c || 'Overdue' == cos.Status__c){
                        Boolean hasANotVoid = false;
                        Boolean datelessThan = false;

                        //Tracking if the invoices have a void or overdue status
                        for(ChargeOver_Invoice__c inv : mappedSubscriptions.get(cos.Id).ChargeOver_Invoices__r){

                            if('Void' != inv.ChargeOver_Invoice_Status__c){
                                hasANotVoid = true;
                                if(inv.Invoice_Date__c <= Date.today()){
                                    datelessThan = true;
                                }
                            }
                        }
                        if(hasANotVoid){
                            if(a.ChargeOver_Invoice_Line_Items__r.isEmpty()){
                                firstYear = true;
                            } else {
                                if(datelessThan){
                                    renewed = true;
                                }
                            }
                        }

                    } 
                    //Separating the finance logic because it includes suspended status
                    if('Current' == cos.Status__c || 'Suspended' == cos.Status__c) {
                        Boolean noVoidOrOverdue = true;
                        for(ChargeOver_Invoice__c inv : mappedSubscriptions.get(cos.Id).ChargeOver_Invoices__r){
                            if('Void' == inv.ChargeOver_Invoice_Status__c
                            || 'Overdue' == inv.ChargeOver_Invoice_Status__c){
                                noVoidOrOverdue = false;
                            }
                        }
                        //If they do not this account qualifies for the current finance status
                        if(noVoidOrOverdue){
                            current = true;
                        }
                    }
                    if('Overdue' == cos.Status__c || 'Suspended' == cos.Status__c){
                        Boolean noVoid = true;
                        Boolean hasPastDue = false;
                        Date monthsAgo = Date.today().addMonths(-15);
                        for(ChargeOver_Invoice__c inv : mappedSubscriptions.get(cos.Id).ChargeOver_Invoices__r){
                            if('Overdue' == inv.ChargeOver_Invoice_Status__c){
                                hasPastDue = true;
                            }
                            if('Void' == inv.ChargeOver_Invoice_Status__c){
                                noVoid = false;
                            }
                        }
                        if(noVoid && (a.ChargeOver_Most_Recent_Payment_Date__c < monthsAgo)){
                            dormant = true;
                        } else if(hasPastDue) {
                            pastDue = true;
                        }
                    }
                    if('Suspended' != cos.Status__c){
                        allSuspended = false;
                    }
                }
            }

            //After checking all the subscriptions, invoices 
            if(firstYear && '1st Year Client' != a.Account_Status__c
                && a.ChargeOver_Most_Recent_Payment_Date__c != null){ //updated criteria -mc
                a.Account_Status__c = '1st Year Client';
                toUpdateAccounts.put(a.Id, a);
            }
            if(allSuspended && !mappedAccounts.get(a.Id).ChargeOver_Subscriptions__r.isEmpty() && 'Suspended' != a.Account_Status__c){
                a.Account_Status__c = 'Suspended';
                toUpdateAccounts.put(a.Id, a);
            }
            if(renewed && 'Renewed Client' != a.Account_Status__c
                && a.ChargeOver_Most_Recent_Payment_Date__c != null){ //updated criteria -mc
                a.Account_Status__c = 'Renewed Client';
                toUpdateAccounts.put(a.Id, a);
            }
            if(partnerSubscribed && 'Partner-Subscribed Prospect' != a.Account_Status__c){ //added new status -mc
                a.Account_Status__c = 'Partner-Subscribed Prospect';
                toUpdateAccounts.put(a.Id, a);
            }
            if(current && 'Current' != a.Finance_Status__c
            && a.ChargeOver_Most_Recent_Payment_Date__c != null){
                a.Finance_Status__c = 'Current';
                toUpdateAccounts.put(a.Id, a);
            }
            if(pastDue && 'Past Due' != a.Finance_Status__c
            && a.ChargeOver_Most_Recent_Payment_Date__c != null){
                a.Finance_Status__c = 'Past Due';
                toUpdateAccounts.put(a.Id, a);
            }
            if(dormant && 'Dormant' != a.Finance_Status__c
            && a.ChargeOver_Most_Recent_Payment_Date__c != null){
                a.Finance_Status__c = 'Dormant';
                toUpdateAccounts.put(a.Id, a);
            }
            
            //If all the subscriptions are cancelled
            if(allCancelled && !mappedAccounts.get(a.Id).ChargeOver_Subscriptions__r.isEmpty()){
                //Account statuses starting with active pending cancel
                if(pendingCancel){
                    if('Active-Pending Cancel (Pause)' != a.Account_Status__c){ // fixed typo (?) 
                        a.Account_Status__c = 'Active-Pending Cancel (Pause)';
                        toUpdateAccounts.put(a.Id, a);
                    }
                //If it doesn't meet that condition for account status, move on to refunded and paused
                } else {
                    //If it has a subscription more than 30% refunded
                    if(refunded){
                        if(a.Account_Status__c != 'Refunded'){
                            a.Account_Status__c = 'Refunded';
                            toUpdateAccounts.put(a.Id, a);
                        }
                    } else {
                        if('Paused' != a.Account_Status__c){
                            if('Partner-Subscribed Prospect' == a.Account_Status__c || 'Partner-Subscribed Prospect' == a.Last_Account_Status__c){
                                a.Account_Status__c = 'Prospect';
                                toUpdateAccounts.put(a.Id, a);
                            } else {
                                a.Account_Status__c = 'Paused Client';
                                toUpdateAccounts.put(a.Id, a);
                            }
                        }                            
                    }
                }
            }
            if(allCancelled && !mappedAccounts.get(a.Id).ChargeOver_Subscriptions__r.isEmpty()
            && a.ChargeOver_Initial_Payment_Date__c != null){
                //Finance statuses
                if(refunded){
                    if(a.Finance_Status__c != 'Refunded'){
                        a.Finance_Status__c = 'Refunded';
                        toUpdateAccounts.put(a.Id, a);
                    } 
                }   else {
                    a.Finance_Status__c = 'Paused';
                    toUpdateAccounts.put(a.Id, a);
                }
            }

        }
        update toUpdateAccounts.values();
    }
}