force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Date_For_Reassignment__c.field-meta.xml
<CustomField>
    <fullName>Date_For_Reassignment__c</fullName>
    <label>Date For Reassignment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1-800Accountant</fullName>
            </value>
            <value>
                <fullName>1800Accountant-Legacy</fullName>
            </value>
            <value>
                <fullName>1-800-Company</fullName>
            </value>
            <value>
                <fullName>1800Corp.com</fullName>
            </value>
            <value>
                <fullName>Agents and Corporations</fullName>
            </value>
            <value>
                <fullName>All Florida Business Solutions</fullName>
            </value>
            <value>
                <fullName>Archetype</fullName>
            </value>
            <value>
                <fullName>Bambee</fullName>
            </value>
            <value>
                <fullName>Bark</fullName>
            </value>
            <value>
                <fullName>Betterfin</fullName>
            </value>
            <value>
                <fullName>BetterLegal</fullName>
            </value>
            <value>
                <fullName>Big Commerce</fullName>
            </value>
            <value>
                <fullName>BizCounsel</fullName>
            </value>
            <value>
                <fullName>BizFilings</fullName>
            </value>
            <value>
                <fullName>BK Search</fullName>
            </value>
            <value>
                <fullName>Bluehost</fullName>
            </value>
            <value>
                <fullName>BPAS</fullName>
            </value>
            <value>
                <fullName>Building Trades</fullName>
            </value>
            <value>
                <fullName>Business.com</fullName>
            </value>
            <value>
                <fullName>Business Licenses</fullName>
            </value>
            <value>
                <fullName>Business Talent Group</fullName>
            </value>
            <value>
                <fullName>Cartinsight</fullName>
            </value>
            <value>
                <fullName>ChaliceNetwork</fullName>
            </value>
            <value>
                <fullName>Clearbanc</fullName>
            </value>
            <value>
                <fullName>ClientBooks</fullName>
            </value>
            <value>
                <fullName>Community Tax</fullName>
            </value>
            <value>
                <fullName>Company.com</fullName>
            </value>
            <value>
                <fullName>Corpnet</fullName>
            </value>
            <value>
                <fullName>Corp Offer</fullName>
            </value>
            <value>
                <fullName>Coverwallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/X1_1_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>X1_1_Scheduled__c</fullName>
    <description>BIT 1-1 sales appointment date/time</description>
    <inlineHelpText>Updating this field will NOT change the event itself. To do that please scroll down to &apos;Activity History&apos;, click on the event you wish to change. Then edit the event and save. However, your changes will NOT be reflected here.</inlineHelpText>
    <label>1-1 Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/X1_1_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>X1_1_Scheduled__c</fullName>
    <inlineHelpText>Updating this field will NOT change the event itself. To do that please scroll down to &apos;Activity History&apos;, click on the event you wish to change. Then edit the event and save. However, your changes will NOT be reflected here.</inlineHelpText>
    <label>1-1 Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ReassignNoShowLeadsBatchableTest.cls
@IsTest
public with sharing class ReassignNoShowLeadsBatchableTest {
    @TestSetup
    static void makeData(){
        List<Account> testAccounts = new List<Account>{
            new Account(Name='testacc'),
            new Account(Name='testacc', X1_1_Scheduled__c=Datetime.now().addDays(-1)),
            new Account(Name='testacc', X1_1_Scheduled__c=Datetime.now().addDays(1)) //this one should be excluded
        };
        insert testAccounts;

        List<Lead> testLeads = new List<Lead>{
            new Lead(FirstName='first', LastName='last', Company='company'),
            new Lead(FirstName='first', LastName='last', Company='company', X1_1_Scheduled__c=Datetime.now().addDays(-1)),
            new Lead(FirstName='first', LastName='last', Company='company', X1_1_Scheduled__c=Datetime.now().addDays(1))            
        };
        insert testLeads;
        
        Datetime curTime = ReassignNoShowLeadsBatchable.roundToHalfHourTime(Datetime.now()).addDays(-1);
        System.debug('curTime: '+curTime);
        List<Event> testEvents = new List<Event>{
            //weekday events
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', Account__c = testAccounts[0].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', Account__c = testAccounts[1].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', Account__c = testAccounts[2].Id),

            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', WhoId = testLeads[0].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', WhoId = testLeads[1].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', WhoId = testLeads[2].Id),

            //events for Monday tests
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime.addDays(-1), Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', Account__c = testAccounts[0].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime.addDays(-1), Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', Account__c = testAccounts[1].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime.addDays(-2), Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', Account__c = testAccounts[2].Id),

            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime.addDays(-1), Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', WhoId = testLeads[0].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime.addDays(-1), Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', WhoId = testLeads[1].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime.addDays(-2), Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', WhoId = testLeads[2].Id),

            //events to ignore:
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='BNA', 
            Subject='Test', DurationInMinutes=5, Appointment_Disposition__c = 'No Show', WhoId = testLeads[0].Id),
            new Event(Lead_Source__c = '1-800Accountant', StartDateTime=curTime, Type_of_Appointment__c ='Tax Savings Analysis', 
            Subject='Test', DurationInMinutes=5, WhatId = testAccounts[1].Id)
        };

        insert testEvents;
    }

    @IsTest 
    static void testBatch(){

        Test.startTest();
        Database.executeBatch(new ReassignNoShowLeadsBatchable(), 20);
        Test.stopTest();

        List<User> generalLeadQueue = [SELECT Id FROM User WHERE Name = 'General Lead Queue' LIMIT 1];
        System.assertEquals(2, [SELECT COUNT() FROM Account WHERE Date_For_Reassignment__c=null AND OwnerId=:generalLeadQueue[0].Id]);
        System.assertEquals(2, [SELECT COUNT() FROM Lead WHERE Date_For_Reassignment__c=null AND OwnerId=:generalLeadQueue[0].Id]);

    }

    @isTest
    public static void testScheduled(){
        System.debug('testScheduled()');
        String CRON_EXP = '0 0 0 3 9 ? 2042';
        Test.startTest();
        String jobId = System.schedule('ReassignNoShowLeadsBatchableTest', CRON_EXP, new ReassignNoShowLeadsBatchable());
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
        NextFireTime
        FROM CronTrigger WHERE id = :jobId];

        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, 
            ct.CronExpression);

        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);

        // Verify the next time the job will run
        System.assert(ct.NextFireTime != null);
        System.debug(ct);
        Test.stopTest();
    }

    @isTest
    public static void testBusinessDays(){
        Assert.areNotEqual(null,  new ReassignNoShowLeadsBatchable().lastBusinessDays);
    }
}