force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Business_Purpose__c</fullName>
    <label>Business Purpose</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <formula>Primary_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/State_of_Formation__c.field-meta.xml
<CustomField>
    <fullName>State_of_Formation__c</fullName>
    <label>State of Formation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>District of Columbia</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Guam</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Louisiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Contact)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <formula>Text (Account.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/Legal_Zoom__c.object-meta.xml
<CustomObject>
    <label>Legal Zoom</label>
    <nameField>
        <label>Legal Zoom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Zoom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Zoom__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Legal Zoom</relationshipLabel>
    <relationshipName>Legal_Zoom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Business_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Business_Purpose__c</fullName>
    <label>Business Purpose</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Legal Zoom</relationshipLabel>
    <relationshipName>Legal_Zoom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Date_Orders__c.field-meta.xml
<CustomField>
    <fullName>Date_Orders__c</fullName>
    <label>Date Orders</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/EMail__c.field-meta.xml
<CustomField>
    <fullName>EMail__c</fullName>
    <label>E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <externalId>true</externalId>
    <label>Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Bill62__Order__c</referenceTo>
    <relationshipLabel>Legal Zoom</relationshipLabel>
    <relationshipName>Legal_Zoom</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DBA</fullName>
            </value>
            <value>
                <fullName>Incorporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Sent_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Customer__c</fullName>
    <label>Sent to Customer</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/State_of_Formation__c.field-meta.xml
<CustomField>
    <fullName>State_of_Formation__c</fullName>
    <label>State of Formation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Org_Defaults__c/Org_Defaults__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org Defaults</label>
</CustomObject>

force-app/main/default/objects/Org_Defaults__c/fields/Default_Product__c.field-meta.xml
<CustomField>
    <fullName>Default_Product__c</fullName>
    <label>Default Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Org_Defaults__c/fields/Subscription_RT__c.field-meta.xml
<CustomField>
    <fullName>Subscription_RT__c</fullName>
    <label>Subscription RT</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchProcessLegalZoom.cls
/*Deprecated
@Name            : BatchProcessLegalZoom 
@Author          : customersuccess@cloud62.com
@Date            : 
@Description     : 
@Last Modify     : 
*/
global class BatchProcessLegalZoom implements Database.Batchable<sObject>, Schedulable{ //
    
    String query = '';
    
    global void execute(SchedulableContext ctx) {
        BatchProcessLegalZoom batch1 = new BatchProcessLegalZoom();
        ID batchprocessid = Database.executeBatch(batch1);
    }
    
    global Database.querylocator start(Database.BatchableContext BC){
    //     //BatchGovernorLimitUtility.insertBatchRun('BatchProcessLegalZoom');
    //     query = 'Select Id, Name, Account__c, Business_Purpose__c, City__c, '
    //         + ' Contact__c, Current_Status__c,  Date_Orders__c, Date_Started__c, '
    //         + ' EMail__c, First_Name__c, Last_Name__c, Mailing_Address__c, Number__c,'
    //         + ' Order__c,   Order_Number__c, Package__c, Phone__c,  Postal_Code__c, '
    //         + ' Process__c, Product_Name__c, Sent_to_Customer__c, State__c, State_of_Formation__c, '
    //         + ' Status__c '
    //         + ' FROM Legal_Zoom__c'
    //         + ' WHERE STATUS__C = NULL OR STATUS__C = \'Pending\' '
    //         //+ ' LIMIT 10'
    //         + '';
    //     if (Test.isRunningTest()){
    //         query += ' LIMIT 200';
    //     }
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext NC, List<sObject> scope){
    //     /*List<Legal_Zoom__c> scopeList = (List<Legal_Zoom__c>) scope;
    //     Set<String> accNameSet = new Set<String>();
    //     Map<String, Legal_Zoom__c> accDetailMap = new Map<String, Legal_Zoom__c>();
    //     List<Account> insertAccount = new List<Account>();
    //     List<Contact> insertContact = new List<Contact>();
    //     List<Bill62__Order__c> insertOrder = new List<Bill62__Order__c>();
    //     List<Bill62__Subscription__c> insertSub = new List<Bill62__Subscription__c>();
    //     Map<String, Bill62__Order__c> orderMap = new Map<String, Bill62__Order__c>();
    //     Map<String, Map<String, Legal_Zoom__c>> emailMap = new Map<String, Map<String, Legal_Zoom__c>>();
    //     Set<String> emailSet = new Set<String>();
        
    //     for (Legal_Zoom__c l : scopeList){
    //         accNameSet.add(l.Name);
    //         accDetailMap.put(l.Name, l);
    //         emailSet.add(l.Email__c);
    //         if (!emailMap.containsKey(l.Name)){
    //             emailMap.put(l.Name, new Map<String, Legal_Zoom__c>());
    //         }
    //         emailMap.get(l.Name).put(l.Email__c, l);
    //     }
        
    //     List<Account> accList = [SELECT ID, NAME FROM ACCOUNT WHERE NAME IN: accNameSet];
    //     Map<String, Account> accMap = new Map<String, Account>();
    //     for (Account a : accList){
    //         accMap.put(a.Name, a);
    //     }
        
    //     for (String x : accNameSet){
    //         if (!accMap.containsKey(x)){
    //             Account newAcc = createAccount(accDetailMap.get(x));
    //             insertAccount.add(newAcc);
    //             accMap.put(x, newAcc);
    //         }
    //     }
        
    //     insert insertAccount;
        
    //     List<Contact> contactList = [SELECT ID, FIRSTNAME, LASTNAME,
    //         ACCOUNTID, ACCOUNT.NAME, Email
    //         FROM CONTACT WHERE Account.Name IN: accNameSet];
    //     Map<String, Map<String, Contact>> conMap = new Map<String, Map<String, Contact>>();
    //     for (Contact c : contactList){
    //         if (!conMap.containsKey(c.Account.Name)){
    //             conMap.put(c.Account.Name, new Map<String, Contact>());
    //         }
    //         conMap.get(c.Account.Name).put(c.Email, c);
    //     }
        
    //     for (String accName : emailMap.keySet()){
    //         if(accMap.containsKey(accName)){
    //             for (Legal_Zoom__c l : emailMap.get(accName).values()){
    //                 Boolean create = false;
    //                 if (!conMap.containsKey(accName)){
    //                     create = true;
    //                 }else if (!conMap.get(accName).containsKey(l.Email__c)){
    //                     create = true;
    //                 }
    //                 if (create){
    //                     Contact newCon = createContact(l, accMap.get(l.Name).Id);
    //                     insertContact.add(newCon);
    //                     if (!conMap.containsKey(accName)){
    //                         conMap.put(accName, new Map<String, Contact>());
    //                     }
    //                     conMap.get(accName).put(l.Email__c, newCon);
    //                 }
    //             }
    //         }   
    //     }
        
    //     insert insertContact;
        
    //     for (Legal_Zoom__c l : scopeList){
    //         Bill62__Order__c o = new Bill62__Order__c();
    //         o.Bill62__Account__c = accMap.get(l.Name).Id;
    //         o.Bill62__Customer__c = conMap.get(l.Name).get(l.Email__c).Id;
    //         o.Bill62__Legacy_Order_ID__c = Integer.valueOf(l.Order_Number__c);
    //         orderMap.put(l.Order_Number__c, o);
    //         insertOrder.add(o); 
    //     }
        
    //     insert insertOrder;
        
    //     for (Legal_Zoom__c l : scopeList){
    //         Bill62__Subscription__c s = new Bill62__Subscription__c();
    //         s.Order__c = orderMap.get(l.Order_Number__c).Id;
    //         s.Bill62__Customer__c = conMap.get(l.Name).get(l.Email__c).Id;
    //         s.Bill62__Product__c = Org_Defaults__c.getOrgDefaults().Default_Product__c; //need to add logic to get the right product
    //         s.RecordTypeId = Org_Defaults__c.getOrgDefaults().Subscription_RT__c; //add logic to get the right RT
    //         s.Bill62__Billing_Frequency__c = 'Monthly';
    //         s.Bill62__Monthly_Billing_Start_Day__c = '1';
    //         s.Bill62__Start_Date__c = Date.today();
    //         insertSub.add(s);
            
    //         l.Account__c = accMap.get(l.Name).Id;
    //         l.Contact__c = conMap.get(l.Name).get(l.Email__c).Id;
    //         l.Order__c = orderMap.get(l.Order_Number__c).Id;
    //         l.Status__c = 'Processed';
    //     }
        
    //     insert insertSub;
        
    //     update scopeList;
    //     */
        
    }
    
    global void finish(Database.BatchableContext BC){
        
    }
    // /*
    // public Account createAccount(Legal_Zoom__c l){
    //     System.debug('Creating account: ' + l.Name);
    //     Account a = new Account();
    //     a.Name = l.Name;
    //     a.Fax = 'warrentest';
    //     return a;
    // }
    
    // public Contact createContact(Legal_Zoom__c l, String accId){
    //     Contact c = new Contact();
    //     c.FirstName = l.First_Name__c;
    //     c.LastName = l.Last_Name__c;
    //     c.Email = l.Email__c;
    //     c.Department = 'warrentest';
    //     c.AccountId = accId;
    //     c.MailingStreet = l.Mailing_Address__c;
    //     c.MailingCity = l.City__c;
    //     c.MailingState = l.State__c;
    //     c.MailingPostalCode = l.Postal_Code__c;
    //     return c;
    // }*/

}