force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payroll_Accountant__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Accountant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payroll Accountant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Support_Accountant__c.field-meta.xml
<CustomField>
    <fullName>Support_Accountant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Support Accountant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Product__c/Account_Product__c.object-meta.xml
<CustomObject>
    <label>Account Product</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Account Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Products</relationshipLabel>
    <relationshipName>Account_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Product__c/fields/Payroll_Accountant__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Accountant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payroll Accountant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Account Products</relationshipLabel>
    <relationshipName>Account_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Product__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Set-Up</fullName>
                <default>true</default>
                <label>Set-Up</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active-On Hold</fullName>
            </value>
            <value>
                <fullName>Suspended / Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Product__c/recordTypes/Payroll.recordType-meta.xml
<RecordType>
    <fullName>Payroll</fullName>
    <active>true</active>
    <label>Payroll</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Business Document</fullName>
            </value>
            <value>
                <fullName>Business Document Center</fullName>
            </value>
            <value>
                <fullName>Business Plan</fullName>
            </value>
            <value>
                <fullName>DO NOT PAY</fullName>
            </value>
            <value>
                <fullName>Entity Set Up and Binder</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Tax Membership</fullName>
            </value>
            <value>
                <fullName>Tax Preparation</fullName>
            </value>
            <value>
                <fullName>Complete Accounting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Selected_Product_Category__c/Selected_Product_Category__c.object-meta.xml
<CustomObject>
    <label>Selected Product Category</label>
    <nameField>
        <label>Selected Product Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selected Product Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Selected_Product_Category__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Selected Product Categories</relationshipLabel>
    <relationshipName>Selected_Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Selected_Product_Category__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Category</label>
    <referenceTo>Product_Category__c</referenceTo>
    <relationshipLabel>Selected Product Categories</relationshipLabel>
    <relationshipName>Selected_Product_Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UtilityBatch.cls
//UtilityBatch
global class UtilityBatch implements Database.Batchable<sObject>,Database.Stateful,Database.AllowsCallouts {

    global UtilityBatch(){

    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Name, Support_Accountant__c FROM Account';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
		List<Account> theList = (List<Account>)scope;
        List<Account_Product__c> insertAPs = new List<Account_Product__c>();
		for(Account a:theList){
            List<String> listPayrollName;
            String prEmployees;
            Integer empQty;
        
            List<Id> listAccountProductIds = new List<Id>();
            List<Id> listPayrollProductIds = new List<Id>();
            Set<Id> setProductIds;
        
            Map<Id, Product2> mapProducts = new Map<Id, Product2>([Select Id
                                                                        , Name 
                                                                    from Product2 
                                                                    where Id IN (Select Bill62__Product__c 
                                                                                from Bill62__Subscription__c 
                                                                                where Bill62__Account__c = :a.Id)]);
        
            // We're only creating Payroll Account Products currently
            List<Product_Category__c> listPCs = [Select Id
                                                        , Name 
                                                from Product_Category__c 
                                                where Name = 'Payroll' 
                                                    and Id IN (Select Product_Category__c 
                                                                from Selected_Product_Category__c 
                                                                where Product__c IN :mapProducts.keySet())];
        
            // This gets us the Product and it's name associated with the Payroll Product Category for this Account
            /*
            Product2 p = [Select Id
                                , Name 
                            from Product2 
                            where Id IN (Select Product__c 
                                        from Selected_Product_Category__c 
                                        where Product_Category__c IN (Select Id 
                                                                    from Product_Category__c 
                                                                    where Name = 'Payroll')
                                        )
                                and Id IN (Select Bill62__Product__c 
                                            from Bill62__Subscription__c 
                                            where Bill62__Account__c = :a.Id)
                            LIMIT 1]);
            */
            List<Bill62__Subscription__c> subs = [Select Bill62__Product__c 
                                            from Bill62__Subscription__c 
                                            where Bill62__Account__c = :a.Id];
            for(Bill62__Subscription__c s : subs){
                listAccountProductIds.add(s.Bill62__Product__c);
            }
            setProductIds = new Set<Id>(listAccountProductIds);
        
            List<Selected_Product_Category__c> spcs = [Select Product__c 
                                        from Selected_Product_Category__c 
                                        where Product_Category__c IN (Select Id 
                                                                    from Product_Category__c 
                                                                    where Name = 'Payroll')];
            for(Selected_Product_Category__c spc : spcs){
                listPayrollProductIds.add(spc.Product__c);
            }
            setProductIds.retainAll(listPayrollProductIds);
            
            if(setProductIds.size() > 0){
                Product2 p = [Select Id, Name from Product2 where Id IN :setProductIds LIMIT 1];
                listPayrollName = p.Name.split('-');
                prEmployees = listPayrollName[1].trim();
                listPayrollName = prEmployees.split(' ');
                empQty = Integer.valueOf(listPayrollName[0]);
             
                // Create Account Products for each Product Category
                for(Product_Category__c pc : listPCs){
                    Account_Product__c ap = new Account_Product__c();
                    ap.RecordTypeId = Schema.SObjectType.Account_Product__c.getRecordTypeInfosByName().get('Payroll').getRecordTypeId();
                    ap.Account__c = a.Id;
                    ap.Product_Category__c = pc.Id;
                    ap.Payroll_Accountant__c = a.Support_Accountant__c;
                    ap.Number_of_Employees__c = empQty;
                    ap.Status__c = 'Set-Up';
                    insertAPs.add(ap);
                }
            } 
        }
        
        insert insertAPs;
    }

    global void finish(Database.BatchableContext BC){
        //don't do nothin!
    }

}