force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>1st Year Client</fullName>
            </value>
            <value>
                <fullName>Renewed Client</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Active-Pending Cancel (Pause)</fullName>
            </value>
            <value>
                <fullName>Paused Client</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChargeOver_Most_Recent_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Most_Recent_Payment_Date__c</fullName>
    <description>The Transaction Date of the most recent ChargeOver Payment Transaction related to the Account</description>
    <label>ChargeOver Most Recent Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Status__c.field-meta.xml
<CustomField>
    <fullName>Finance_Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>A checkbox to indicate that the Account was created for a Partner</description>
    <label>Partner Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Status__c/Account_Status__c.object-meta.xml
<CustomObject>
    <label>Account Status</label>
    <nameField>
        <label>Account Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountStatusBatch.cls
global class AccountStatusBatch implements Database.Batchable<sObject>, Schedulable {
    public String batchQuery = 
          'SELECT Id, Name, Account_Status__c, ChargeOver_Most_Recent_Payment_Date__c, Finance_Status__c, Blacklisted__c, Business_Account__c, Partner_Account__c  '
        + 'FROM Account '
        + 'WHERE Account_Status__c != \'Blacklisted\' '
        + 'AND Account_Status__c != \'Business Account\' '
        + 'AND Account_Status__c != \'Partner Account\' '
        + 'AND Account_Status__c != \'Prospect\' '
        ;

    public AccountStatusBatch() {}
    public Database.QueryLocator start(Database.BatchableContext bc)  {
        return Database.getQueryLocator(batchQuery);
    }
    public void execute(SchedulableContext context) {
        AccountStatusBatch assignStatus = new AccountStatusBatch();
        Database.executeBatch(assignStatus, 200);
    }
    public void execute(Database.BatchableContext bc, List<Account> accounts){
        this.execute(accounts);
    }
    public void execute(List<Account> accounts) {
        List<Id> accountIds = new List<Id>();
        List<Account> toUpdateAccounts = new List<Account>();
        for(Account a : accounts){
            a.Account_Status__c = 'Prospect';
            toUpdateAccounts.add(a);
            accountIds.add(a.Id);
        }
        update toUpdateAccounts;
        AccountStatusHandler.assignAccountStatus(accountIds);
    }

    public void finish(Database.BatchableContext bc){}     
}