force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>1st Year Client</fullName>
            </value>
            <value>
                <fullName>Renewed Client</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Active-Pending Cancel (Pause)</fullName>
            </value>
            <value>
                <fullName>Paused Client</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1-800Accountant</fullName>
            </value>
            <value>
                <fullName>1800Accountant-Legacy</fullName>
            </value>
            <value>
                <fullName>1-800-Company</fullName>
            </value>
            <value>
                <fullName>1800Corp.com</fullName>
            </value>
            <value>
                <fullName>Agents and Corporations</fullName>
            </value>
            <value>
                <fullName>All Florida Business Solutions</fullName>
            </value>
            <value>
                <fullName>Archetype</fullName>
            </value>
            <value>
                <fullName>Bambee</fullName>
            </value>
            <value>
                <fullName>Bark</fullName>
            </value>
            <value>
                <fullName>Betterfin</fullName>
            </value>
            <value>
                <fullName>BetterLegal</fullName>
            </value>
            <value>
                <fullName>Big Commerce</fullName>
            </value>
            <value>
                <fullName>BizCounsel</fullName>
            </value>
            <value>
                <fullName>BizFilings</fullName>
            </value>
            <value>
                <fullName>BK Search</fullName>
            </value>
            <value>
                <fullName>Bluehost</fullName>
            </value>
            <value>
                <fullName>BPAS</fullName>
            </value>
            <value>
                <fullName>Building Trades</fullName>
            </value>
            <value>
                <fullName>Business.com</fullName>
            </value>
            <value>
                <fullName>Business Licenses</fullName>
            </value>
            <value>
                <fullName>Business Talent Group</fullName>
            </value>
            <value>
                <fullName>Cartinsight</fullName>
            </value>
            <value>
                <fullName>ChaliceNetwork</fullName>
            </value>
            <value>
                <fullName>Clearbanc</fullName>
            </value>
            <value>
                <fullName>ClientBooks</fullName>
            </value>
            <value>
                <fullName>Community Tax</fullName>
            </value>
            <value>
                <fullName>Company.com</fullName>
            </value>
            <value>
                <fullName>Corpnet</fullName>
            </value>
            <value>
                <fullName>Corp Offer</fullName>
            </value>
            <value>
                <fullName>Coverwallet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pitched_Date__c.field-meta.xml
<CustomField>
    <fullName>Pitched_Date__c</fullName>
    <label>Consulted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/X1_1_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>X1_1_Scheduled__c</fullName>
    <description>BIT 1-1 sales appointment date/time</description>
    <inlineHelpText>Updating this field will NOT change the event itself. To do that please scroll down to &apos;Activity History&apos;, click on the event you wish to change. Then edit the event and save. However, your changes will NOT be reflected here.</inlineHelpText>
    <label>1-1 Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account_Status__c/Account_Status__c.object-meta.xml
<CustomObject>
    <label>Account Status</label>
    <nameField>
        <label>Account Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Pitched_Date__c.field-meta.xml
<CustomField>
    <fullName>Pitched_Date__c</fullName>
    <description>To track date/time of pitch</description>
    <label>Consulted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/X1_1_Scheduled__c.field-meta.xml
<CustomField>
    <fullName>X1_1_Scheduled__c</fullName>
    <inlineHelpText>Updating this field will NOT change the event itself. To do that please scroll down to &apos;Activity History&apos;, click on the event you wish to change. Then edit the event and save. However, your changes will NOT be reflected here.</inlineHelpText>
    <label>1-1 Scheduled</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead_Reassignment_Queue__mdt/Lead_Reassignment_Queue__mdt.object-meta.xml
<CustomObject>
    <description>Used in Update_Lead_Owner_to_Queue &amp; Update_Account_Owner_to_Lead_Queue &amp; trigger LeadPreventOwnerChange to access Queue information.</description>
    <label>Lead Reassignment Queue</label>
    <pluralLabel>Lead Reassignment Queues</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Reassignment_Queue__mdt/fields/Queue_Object_Type__c.field-meta.xml
<CustomField>
    <fullName>Queue_Object_Type__c</fullName>
    <label>Queue Object Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User</fullName>
                <default>true</default>
                <label>User</label>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Reassignment_Queue__mdt/fields/Queue_Type__c.field-meta.xml
<CustomField>
    <fullName>Queue_Type__c</fullName>
    <label>Queue Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General Lead Queue</fullName>
                <default>true</default>
                <label>General Lead Queue</label>
            </value>
            <value>
                <fullName>Dead Leads Queue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Reassignment_Queue__mdt/fields/Reassignment_Queue_Name__c.field-meta.xml
<CustomField>
    <fullName>Reassignment_Queue_Name__c</fullName>
    <description>Used in Update_Lead_Owner_to_Queue</description>
    <inlineHelpText>Must match a Queue/User in Salesforce</inlineHelpText>
    <label>Reassignment Queue Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Update_Account_Owner_Test.cls
@isTest
private class Update_Account_Owner_Test{  
    @IsTest
    private static void testUpdateAccountOwnerToQueue() {
        Lead_Reassignment_Queue__mdt queueMetadata = [
            SELECT Id, MasterLabel, Queue_Object_Type__c, Reassignment_Queue_Name__c 
            FROM Lead_Reassignment_Queue__mdt 
            WHERE Queue_Type__c = 'General Lead Queue' 
            LIMIT 1
        ];
        String m_query = 'SELECT Id FROM '+ queueMetadata.Queue_Object_Type__c +' WHERE Name = \''+queueMetadata.Reassignment_Queue_Name__c+'\' LIMIT 1';
        Id queueId = Database.query(m_query).Id;

        //first time through with default Unpitched Accounts query
        Update_Account_Owner_to_Lead_Queue batchJob = new Update_Account_Owner_to_Lead_Queue();
        batchJob.setAccounts();
        batchJob.manualExecution();

        //second time through with Partner Accounts query
        batchJob.establishQuery('Tier 1 - Pitched (Account)');
        batchJob.setAccounts();
        batchJob.manualExecution();

        //third time through with Pitched Accounts query
        batchJob.establishQuery('Tier 1 - Unpitched (Account)');
        batchJob.setAccounts();
        batchJob.manualExecution();

        List<Account> testPartnerAccounts = [SELECT Id, OwnerId FROM Account WHERE OwnerId = :queueId AND Lead_Source__c != 'Bark'];
        System.assertEquals(false, testPartnerAccounts.isEmpty(), 'No Partner Accounts had the Owner Reassigned');
        System.assertEquals(5, testPartnerAccounts.size(), 'All Partner Accounts should be converted');

        List<Account> testPitchedBarkLeads = [SELECT Id, OwnerId FROM Account WHERE OwnerId = :queueId AND Lead_Source__c = 'Bark' AND X1_1_Scheduled__c != null];
        System.assertEquals(false, testPitchedBarkLeads.isEmpty(), 'No Pitched Bark Accounts had the Owner Reassigned');
        System.assertEquals(5, testPitchedBarkLeads.size(), 'All Pitched Bark Accounts should be converted');

        List<Account> testUnpitchedBarkLeads = [SELECT Id, OwnerId FROM Account WHERE OwnerId = :queueId AND Lead_Source__c = 'Bark' AND X1_1_Scheduled__c = null];                                           
        System.assertEquals(false, testUnpitchedBarkLeads.isEmpty(), 'No Unpitched Bark Accounts had the Owner Reassigned');
        System.assertEquals(5, testUnpitchedBarkLeads.size(), 'All Unpitched Bark Accounts should be converted');

        Test.startTest();
        Update_Account_Owner_to_Lead_Queue batchJob2 = new Update_Account_Owner_to_Lead_Queue();
        Database.executeBatch(batchJob2, 1);
        Test.stopTest();
    }

    @TestSetup
    private static void testSetup() {
        Id profileId = [SELECT Id, Name FROM Profile WHERE Name = 'Sales Manager' LIMIT 1].Id;

        User testUser = TestDataGenerator.createTestUser(profileId);
        insert testUser;

        List<Account> toInsertAccounts = new List<Account>();
        //Make 5 Partner Accounts
        for (Integer i = 0; i < 5; i++) {
            Account account = TestDataGenerator.createTestAccount(testUser.Id);
            account.Account_Status__c = 'No Sale';
            toInsertAccounts.add(account);
        }

        //Make 5 Unpitched Bark Accounts
        for (Integer i = 0; i < 5; i++) {
            Account account = TestDataGenerator.createTestAccount(testUser.Id);
            account.Lead_Source__c = 'Bark';
            account.Pitched_Date__c = null;
            account.Account_Status__c = 'No Sale';
            toInsertAccounts.add(account);
        }

        //Make 5 Pitched Bark Accounts
        for (Integer i = 0; i < 5; i++) {
            Account account = TestDataGenerator.createTestAccount(testUser.Id);
            account.Lead_Source__c = 'Bark';
            account.Account_Status__c = 'No Sale';
            account.X1_1_Scheduled__c = Date.today().addDays(-1);
            toInsertAccounts.add(account);
        }
        insert toInsertAccounts;
    }
     
}