force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/Active_Subscription_Line__c.object-meta.xml
<CustomObject>
    <label>Active Subscription Line</label>
    <nameField>
        <label>Active Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/Active_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Active Subscription</label>
    <nameField>
        <label>Active Subscriptions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscriptions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscriptions</relationshipLabel>
    <relationshipName>Active_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Active Subscriptions</relationshipLabel>
    <relationshipName>Active_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/ChargeOver_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Invoice Line Item</label>
    <nameField>
        <label>ChargeOver Invoice Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Invoice Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/ASL_Renewal_Trigger__c.field-meta.xml
<CustomField>
    <fullName>ASL_Renewal_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checking this box will trigger a manual run of the ASL Renewal code</description>
    <inlineHelpText>Checking this box will trigger a manual run of the ASL Renewal code</inlineHelpText>
    <label>ASL Renewal Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/First_Obligation_ID__c.field-meta.xml
<CustomField>
    <fullName>First_Obligation_ID__c</fullName>
    <label>First Obligation ID</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Is_Obligation__c.field-meta.xml
<CustomField>
    <fullName>Is_Obligation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Obligation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Number_of_Recurs__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Recurs__c</fullName>
    <label># of times this has recurred</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Financing</fullName>
            </value>
            <value>
                <fullName>2 Pay</fullName>
            </value>
            <value>
                <fullName>3 Pay</fullName>
            </value>
            <value>
                <fullName>4 Pay</fullName>
            </value>
            <value>
                <fullName>6 Pay</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Type__c</fullName>
    <label>Payment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/ChargeOver_Subscription__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription</label>
    <nameField>
        <label>ChargeOver Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscriptions</relationshipLabel>
    <relationshipName>ChargeOver_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled due to non-payment</fullName>
            </value>
            <value>
                <fullName>Cancelled manually</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Trial Period Over</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>The date the ChargeOver subscription was created.</description>
    <label>Subscription Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/ChargeOver_Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription Line Item</label>
    <nameField>
        <label>ChargeOver Subscription Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <label>Subscription Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Billing_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Billing_Frequency__c</fullName>
    <label>Billing Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Semi-Annual</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Fulfillable_Product_for_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Fulfillable_Product_for_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that a product is fulfillable and needs a new Active Subscription Line upon a renewal</description>
    <inlineHelpText>If checked, will create a new Active Subscription Line upon renewal of the product</inlineHelpText>
    <label>Fulfillable Product for Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChargeoverInvoiceLineTriggerHandler.cls
public with sharing class ChargeoverInvoiceLineTriggerHandler {
    public static void afterUpdate(Map<Id, ChargeOver_Invoice_Line_Item__c> oldItems, List<ChargeOver_Invoice_Line_Item__c> newItems){
        List<ChargeOver_Invoice_Line_Item__c> toggledItems = new List<ChargeOver_Invoice_Line_Item__c>();
        for(ChargeOver_Invoice_Line_Item__c item : newItems){
            if(oldItems.get(item.Id).ASL_Renewal_Trigger__c != item.ASL_Renewal_Trigger__c){
                toggledItems.add(item);
            }
        }
        if(!toggledItems.isEmpty()){
            afterInsert(toggledItems);
        }
    }

    public static void afterInsert(List<ChargeOver_Invoice_Line_Item__c> items){
        System.debug('ChargeoverInvoiceLineTriggerHandler.afterInsert()');
        List<Id> yearlyItemIds = new List<Id>();
        List<Id> monthlyItemIds = new List<Id>();
        for(ChargeOver_Invoice_Line_Item__c item : items){
            Boolean isRenewal = (item.Payment_Type__c == 'Renewal' || (item.Payment_Terms__c != 'Monthly' && !item.Is_Obligation__c && item.First_Obligation_ID__c != null));
            Boolean isMonthly = (item.Payment_Terms__c == 'Monthly' && item.Number_of_Recurs__c > 1 && Math.mod((Integer)item.Number_of_Recurs__c, 12)==1);
            
            if(isRenewal || isMonthly){ 
                System.debug('added item: '+item.Id+' '+item.Payment_Type__c+' '+item.Payment_Terms__c);
                yearlyItemIds.add(item.Id);                
            } else {
                System.debug('item not added: '+item.Id+' '+item.Payment_Type__c+' '+item.Payment_Terms__c);
            }
        }

        for(Id itemId : yearlyItemIds){
            syncAnnualItem(itemId);
        }
    }


    @future
    public static void syncAnnualItem(Id itemId){
        System.debug('ChargeoverInvoiceLineTriggerHandler.syncAnnualItem()');
        ChargeOver_Invoice_Line_Item__c item = 
        [SELECT Id,
        Rate__c,
        Quantity__c,
        Account__r.Id,
        Product__r.Id,
        Product__r.Fulfillable_Product_for_Renewal__c,
        Product__r.Family, //category
        Product__r.Billing_Frequency__c,
        ChargeOver_Subscription_Line_Item__r.Id,
        ChargeOver_Subscription_Line_Item__r.Status__c,
        ChargeOver_Subscription_Line_Item__r.Subscription_Start_Date__c,
        ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Id,
        ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Name,
        ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Customer_Number__c,
        ChargeOver_Subscription_Line_Item__r.Chargeover_Subscription__r.Id
        FROM ChargeOver_Invoice_Line_Item__c 
        WHERE Id = :itemId LIMIT 1];
        System.debug(item);

        Boolean isTaxPrep = (item.Product__r.Billing_Frequency__c == 'Annual' && item.Product__r.Fulfillable_Product_for_Renewal__c);

        if(isTaxPrep){
            List<Active_Subscription_Line__c> newAsls = new List<Active_Subscription_Line__c>();
            for(integer i=0; i<item.Quantity__c; i++){
                Active_Subscription_Line__c newAsl = new Active_Subscription_Line__c(
                    Name = item.ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Name,
                    Account__c = item.Account__r.Id,
                    Customer_Number__c = item.ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Customer_Number__c,
                    ChargeOver_Subscription__c = item.ChargeOver_Subscription_Line_Item__r.Chargeover_Subscription__r.Id,
                    ChargeOver_Subscription_Line_Item__c = item.ChargeOver_Subscription_Line_Item__r.Id,
                    Active_Subscription__c = item.ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Id,
                    Unique_Identifier__c = item.Product__r.Id+''+item.Account__r.Id,
                    Status__c = item.ChargeOver_Subscription_Line_Item__r.Status__c,
                    Product__c = item.Product__r.Id,
                    Category__c = item.Product__r.Family,
                    Subscription_Amount__c = item.Rate__c,
                    Start_Date__c = item.ChargeOver_Subscription_Line_Item__r.Subscription_Start_Date__c.date(),
                    Created_by_Renewal__c = true
                );
                newAsls.add(newAsl);
            }
            
    
            System.debug(newAsls);
            //Savepoint sp = Database.setSavepoint();
            List<Database.SaveResult> res = Database.insert(newAsls);
            for(Database.SaveResult sr : res){
                System.debug(res);
            }            
            //manually trigger rollup logic
            //ChargeOver_ActiveSubTriggerHandler.updateTotalQuantity(new List<Active_Subscriptions__c>{new Active_Subscriptions__c(Id=item.ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Id)});
            //Database.rollback(sp);
            Active_Subscriptions__c sub = new Active_Subscriptions__c(Id = item.ChargeOver_Subscription_Line_Item__r.Active_Subscription__r.Id);
            update sub;
    
            //ChargeOver_Invoice_Line_Item__c.Unique_Identifier__c = 
            //   ChargeOver_Invoice_Line_Item__c.Product__c + ChargeOver_Invoice_Line_Item__c.Account__c
        } else {
            System.debug('item not tax prep: '+item.Id+' '+item.Product__r.Billing_Frequency__c+' '+ item.Product__r.Fulfillable_Product_for_Renewal__c);
        }
        
    }
}