force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote__c/ChargeOver_Quote__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Quote</label>
    <nameField>
        <label>ChargeOver Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Quotes</relationshipLabel>
    <relationshipName>ChargeOver_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote__c/fields/Date_Time_Invoice_Being_Held_Until__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Invoice_Being_Held_Until__c</fullName>
    <label>Date/Time Invoice Being Held Until</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote__c/fields/Installment_Payment_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Installment_Payment_Schedule__c</fullName>
    <label>Installment Payment Schedule</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote__c/fields/Quote_Created__c.field-meta.xml
<CustomField>
    <fullName>Quote_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <description>The Quote number for the Salesforce Quote</description>
    <label>Quote Number</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/ChargeOver_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Quote Line Item</label>
    <nameField>
        <label>ChargeOver Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Quote Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/Applied_Account__c.field-meta.xml
<CustomField>
    <fullName>Applied_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary (Personal) or Secondary (Business) Account that the ChargeOver Subscription Line Item was purchased to</description>
    <label>Applied Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Quote Line Items (Applied Account)</relationshipLabel>
    <relationshipName>ChargeOver_Quote_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/ChargeOver_Quote__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Quote</label>
    <referenceTo>ChargeOver_Quote__c</referenceTo>
    <relationshipLabel>ChargeOver Quote Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/HTML_Description__c.field-meta.xml
<CustomField>
    <fullName>HTML_Description__c</fullName>
    <description>the sales, marketing, and quote description of the product</description>
    <label>HTML Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/of_Free_Trial_Cycles_Cycles_to_Skip__c.field-meta.xml
<CustomField>
    <fullName>of_Free_Trial_Cycles_Cycles_to_Skip__c</fullName>
    <label># of Free Trial Cycles / Cycles to Skip</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/of_times_this_should_recur__c.field-meta.xml
<CustomField>
    <fullName>of_times_this_should_recur__c</fullName>
    <label># of times this should recur</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ChargeOver Quote Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <description>Invoice and technical description of the product</description>
    <label>Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/HTML_Description__c.field-meta.xml
<CustomField>
    <fullName>HTML_Description__c</fullName>
    <label>HTML Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Months_Before_Effective_Price_Increase__c.field-meta.xml
<CustomField>
    <fullName>Months_Before_Effective_Price_Increase__c</fullName>
    <description>The number of months before the scheduled price increase</description>
    <label>Months Before Effective Price Increase</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Price_Increase_Percent__c.field-meta.xml
<CustomField>
    <fullName>Price_Increase_Percent__c</fullName>
    <description>The percentage that a product&apos;s price should increase upon the 1st year&apos;s renewal</description>
    <inlineHelpText>The percentage that a product&apos;s price should increase upon the 1st year&apos;s renewal</inlineHelpText>
    <label>Price Increase Percent</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Setup_Fee__c.field-meta.xml
<CustomField>
    <fullName>Setup_Fee__c</fullName>
    <label>Setup Fee</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
            <value>
                <fullName>Annual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChargeOver_Quote_Test.cls
@IsTest
public with sharing class ChargeOver_Quote_Test
{

    @TestSetup
    private static void dataGenerator()
    {
        Account act = new Account(Name='I am an account');
        insert act;
        
        Product2 p = new Product2(
            Name='Test product',
            Setup_Fee__c='One-Time'
        	);
        insert p;
        
        Product2 p2 = new Product2(
            Name='Test product 2', 
            Price_Increase_Percent__c=7, 
            Months_Before_Effective_Price_Increase__c=12);
        insert p2;

        ChargeOver_Quote__c quote = new ChargeOver_Quote__c(Account__c=act.Id, Installment_Payment_Schedule__c=4, Quote_Number__c='1',Redirect_URL__c='http://blog.com');
        insert quote;

        ChargeOver_Quote_Line_Item__c sli1 = new ChargeOver_Quote_Line_Item__c(
            ChargeOver_Quote__c=quote.Id, 
            Product__c=p.Id, 
            HTML_Description__c='<b>test</b>', 
            of_Free_Trial_Cycles_Cycles_to_Skip__c=1, 
            Date_Time_Invoice_Being_Held_Until__c='2022-01-01'
        	);
        
		insert sli1;
        
        ChargeOver_Quote_Line_Item__c sli2 = new ChargeOver_Quote_Line_Item__c(
            ChargeOver_Quote__c=quote.Id, 
            Product__c=p.Id, 
			HTML_Description__c='<b>test</b>', 
            Product_Description__c='test', 
			of_times_this_should_recur__c=3,
			Applied_Account__c=act.Id,
            Contract_Amount__c=1000
        	);
        
		insert sli2;
        
        ChargeOver_Quote_Line_Item__c sli3 = new ChargeOver_Quote_Line_Item__c(
            ChargeOver_Quote__c=quote.Id, 
            Product__c=p.Id, 
            HTML_Description__c='<b>test</b>', 
            of_Free_Trial_Cycles_Cycles_to_Skip__c=1, 
            Date_Time_Invoice_Being_Held_Until__c='2022-01-01'
        	);
        
		insert sli3;
        
        ChargeOver_Quote_Line_Item__c sli4 = new ChargeOver_Quote_Line_Item__c(
            ChargeOver_Quote__c=quote.Id, 
            Product__c=p.Id, 
            HTML_Description__c='<b>test</b>', 
            Date_Time_Invoice_Being_Held_Until__c='2023-01-01'
        	);
        
		insert sli4;
    }

    @IsTest
    private static void testQuoteCreation()
    {
        ChargeOver_Quote__c quote = [SELECT Id FROM ChargeOver_Quote__c LIMIT 1];
        System.assertNotEquals(null, quote);
    }

    @IsTest
    private static void testQuoteUpdate()
    {
        ChargeOver_Quote__c quote = [SELECT Id, Account__c FROM ChargeOver_Quote__c LIMIT 1];
        System.assertNotEquals(null, quote);

        Test.startTest();

            quote.Status__c = 'Active';
            quote.Quote_Created__c = true;
            update quote;

        Test.stopTest();

        //Needs some kind of assertion.
    }

    @IsTest
    private static void testQuoteDelete()
    {
        ChargeOver_Quote__c quote = [SELECT Id, Account__c FROM ChargeOver_Quote__c LIMIT 1];
        System.assertNotEquals(null, quote);

        Test.startTest();

            delete quote;

        Test.stopTest();

        ChargeOver_Quote__c deleted = [SELECT Id FROM ChargeOver_Quote__c WHERE IsDeleted = TRUE LIMIT 1 ALL ROWS];
        System.assertNotEquals(null, deleted);
    }
}