force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Business Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChargeOver_ID__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_ID__c</fullName>
    <externalId>true</externalId>
    <label>ChargeOver ID</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/IS_FROM_CHARGEOVER__c.field-meta.xml
<CustomField>
    <fullName>IS_FROM_CHARGEOVER__c</fullName>
    <defaultValue>false</defaultValue>
    <description>INTERNAL SYNC - do not manually edit</description>
    <label>Is from ChargeOver?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/LAST_SOURCE__c.field-meta.xml
<CustomField>
    <fullName>LAST_SOURCE__c</fullName>
    <description>INTERNAL SYNC - do not manually edit</description>
    <label>INTERNAL SYNC - Last Source</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_First_Name__c</fullName>
    <formula>Primary_Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Last_Name__c</fullName>
    <formula>Primary_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Phone__c</fullName>
    <formula>Primary_Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Contact Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Ready_for_sync_to_ChargeOver__c.field-meta.xml
<CustomField>
    <fullName>Ready_for_sync_to_ChargeOver__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready for sync to ChargeOver</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/Active_Subscription_Line__c.object-meta.xml
<CustomObject>
    <label>Active Subscription Line</label>
    <nameField>
        <label>Active Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscription Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Applied_Account__c.field-meta.xml
<CustomField>
    <fullName>Applied_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account that the Active Subscription Line is related to. This determines entitlements within the portal</description>
    <label>Applied Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscription Lines (Applied Account)</relationshipLabel>
    <relationshipName>Active_Subscription_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/ChargeOver_Subscription__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription</label>
    <referenceTo>ChargeOver_Subscription__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Active Subscription Lines</relationshipLabel>
    <relationshipName>Active_Subscription_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscription_Line__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/ChargeOver_Subscription__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription</label>
    <nameField>
        <label>ChargeOver Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscriptions</relationshipLabel>
    <relationshipName>ChargeOver_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/IS_FROM_CHARGEOVER__c.field-meta.xml
<CustomField>
    <fullName>IS_FROM_CHARGEOVER__c</fullName>
    <defaultValue>false</defaultValue>
    <description>INTERNAL SYNC - do not edit manually</description>
    <label>Is from ChargeOver?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Trial Period</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Cancelled due to non-payment</fullName>
            </value>
            <value>
                <fullName>Cancelled manually</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Trial Period Over</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/ChargeOver_Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription Line Item</label>
    <nameField>
        <label>ChargeOver Subscription Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Active_Subscription_Line__c.field-meta.xml
<CustomField>
    <fullName>Active_Subscription_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Active Subscription Line</label>
    <referenceTo>Active_Subscription_Line__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Applied_Account__c.field-meta.xml
<CustomField>
    <fullName>Applied_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applied Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items (Applied Account)</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription</label>
    <referenceTo>ChargeOver_Subscription__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/IS_FROM_CHARGEOVER__c.field-meta.xml
<CustomField>
    <fullName>IS_FROM_CHARGEOVER__c</fullName>
    <defaultValue>false</defaultValue>
    <description>INTERNAL SYNC - do not manually edit</description>
    <label>Is from ChargeOver?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/LAST_SOURCE__c.field-meta.xml
<CustomField>
    <fullName>LAST_SOURCE__c</fullName>
    <description>INTERNAL SYNC - do not edit manually</description>
    <label>Last Source</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active - Pending Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <formula>Text (Account.Account_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/SOW_Description__c.field-meta.xml
<CustomField>
    <fullName>SOW_Description__c</fullName>
    <label>SOW Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Standard_Price__c.field-meta.xml
<CustomField>
    <fullName>Standard_Price__c</fullName>
    <label>Standard Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ZZ_Primary_Category__c.field-meta.xml
<CustomField>
    <fullName>ZZ_Primary_Category__c</fullName>
    <description>Business, Personal, or business and personal</description>
    <label>ZZ Primary Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Personal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerTest.cls
@IsTest
private class AccountTriggerHandlerTest
{
    private static final User PORTAL_USER = [SELECT Id FROM User WHERE Alias = 'drepl'];

    @TestSetup
    private static void createTestData()
    {

        System.runAs(PORTAL_USER)
        {
            Account pAccount = new Account(Name='Personal', Business_Account__c=false);
            insert pAccount;

            Contact cont = new Contact(AccountId=pAccount.Id, LastName='Pho', FirstName='Soup');
            insert cont;

            Product2 prod = new Product2(Name='TestProduct',Standard_Price__c=1.0,Description='Test',Family='Bookkeeping',SOW_Description__c='Test',ZZ_Primary_Category__c='Business');
            insert prod;

            //There is a queueable job that relates the ActiveSub to the SLI record.
            //Insert these two here because in the deletion process it cannot otherwise keep track of the Queueable job order. -SReyes

            ChargeOver_Subscription__c sliSub = new ChargeOver_Subscription__c(Name='Test',Account__c=pAccount.Id);
            insert sliSub;

            ChargeOver_Subscription_Line_Item__c sli = new ChargeOver_Subscription_Line_Item__c(ChargeOver_Subscription__c=sliSub.Id, Quantity__c=2, Account__c=pAccount.Id, Product__c=prod.Id, Status__c='Active',Price_Per_Unit__c=10.0);
            insert sli;

            sli.Price_Per_Unit__c=10;
            update sli;

            System.debug(LoggingLevel.DEBUG, 'ASL should exist :: ' + [SELECT Id FROM Active_Subscription_Line__c WHERE Account__c = :pAccount.Id]);

            Account nAccount = new Account(
                    Name='Business',
                    Business_Account__c=true,
                    IS_FROM_CHARGEOVER__c=true,
                    Ready_for_sync_to_ChargeOver__c=true,
                    BillingState='TX',
                    BillingStreet='121 Birdseed Way',
                    BillingPostalCode='77584',
                    BillingCity='Pearland',
                    BillingCountry='USA',
                    ChargeOver_ID__c='123'
            );
            insert nAccount;

            insert new AccountContactRelation(AccountId=nAccount.Id,ContactId=cont.Id);
        }
    }
    @IsTest
    private static void testSetupResultsCheck()
    {
        Account act = [SELECT Id FROM Account WHERE Business_Account__c = TRUE LIMIT 1];
        Test.startTest();
            Active_Subscription_Line__c related = [SELECT Id FROM Active_Subscription_Line__c WHERE Applied_Account__c = :act.Id LIMIT 1];
        Test.stopTest();
        System.assertNotEquals(null, related, 'should have found related ASL for account :: ' + act);
        System.debug('testBehavior completed');
    }

    @IsTest
    private static void testAfterUpdateTriggerMethod()
    {
        Account[] accounts = [
                SELECT Id, IS_FROM_CHARGEOVER__c,LAST_SOURCE__c,Ready_for_sync_to_ChargeOver__c,Primary_Contact_Email__c,Primary_Contact_First_Name__c, Name,
                        Primary_Contact_Last_Name__c,Primary_Contact_Phone__c, BillingCity, BillingState, BillingStreet, BillingPostalCode, BillingCountry,ChargeOver_ID__c
                FROM Account];
        Boolean successfulRun = false;

        Integer counter = 0;
        for(Account act : accounts)
        {
            act.ChargeOver_ID__c = act.ChargeOver_ID__c + counter;
            counter++;
        }

        Test.startTest();
        try {
//            AccountTriggerHandler.chargeOverAfterUpdate(accounts);
            update accounts;

            successfulRun = true;
        }catch(Exception err){
            System.debug('test.chargeOverAfterUpdate() failed with err :: ' + err);
        }
        Test.stopTest();

        System.assertNotEquals(false, successfulRun, 'should be true from successful run of testAfterUpdateTriggerMethod() test class.');
    }

    @IsTest
    private static void testAfterUpdateTriggerMethod2()
    {
        Account[] accounts = [
                SELECT Id, IS_FROM_CHARGEOVER__c,LAST_SOURCE__c,Ready_for_sync_to_ChargeOver__c,Primary_Contact_Email__c,Primary_Contact_First_Name__c, Name,
                        Primary_Contact_Last_Name__c,Primary_Contact_Phone__c, BillingCity, BillingState, BillingStreet, BillingPostalCode, BillingCountry,ChargeOver_ID__c
                FROM Account];
        for(Account act : accounts){ act.ChargeOver_ID__c = null; }

        Boolean successfulRun = false;
        Test.startTest();
        try {
            update accounts;
//            AccountTriggerHandler.chargeOverAfterUpdate(accounts);
            successfulRun = true;
        }catch(Exception err){
            System.debug('test.chargeOverAfterUpdate2() failed with err :: ' + err);
        }
        Test.stopTest();

        System.assertNotEquals(false, successfulRun, 'should be true from successful run of testAfterUpdateTriggerMethod() test class.');
    }

    @IsTest
    private static void testAfterInsertTriggerMethod()
    {
        Account[] accounts = [
                SELECT Id, IS_FROM_CHARGEOVER__c,LAST_SOURCE__c,Ready_for_sync_to_ChargeOver__c,Primary_Contact_Email__c,Primary_Contact_First_Name__c, Name,
                        Primary_Contact_Last_Name__c,Primary_Contact_Phone__c, BillingCity, BillingState, BillingStreet, BillingPostalCode, BillingCountry,ChargeOver_ID__c
                FROM Account];
        Boolean successfulRun = false;
        Test.startTest();
        try {
            AccountTriggerHandler.chargerOverAfterInsert(accounts);
            successfulRun = true;
        }catch(Exception err){
            System.debug('test.chargerOverAfterInsert() failed with err :: ' + err);
        }
        Test.stopTest();

        System.assertNotEquals(false, successfulRun, 'should be true from successful run of testAfterInsertTriggerMethod() test class.');
    }
}