force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>1st Year Client</fullName>
            </value>
            <value>
                <fullName>Renewed Client</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Active-Pending Cancel (Pause)</fullName>
            </value>
            <value>
                <fullName>Paused Client</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
                <color>#78C953</color>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>Call Back Set</fullName>
                <color>#E27001</color>
                <label>Call Back Set</label>
            </value>
            <value>
                <fullName>1-1 Request</fullName>
                <color>#66E9BD</color>
                <label>1-1 Request</label>
            </value>
            <value>
                <fullName>1-1 No Show</fullName>
                <color>#0B24BE</color>
                <label>1-1 No Show</label>
            </value>
            <value>
                <fullName>1-1 Cancelled</fullName>
                <color>#419249</color>
                <label>1-1 Cancelled</label>
            </value>
            <value>
                <fullName>Pitched</fullName>
                <color>#B6E32E</color>
                <label>Pitched</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <color>#641CCF</color>
                <label>Qualified</label>
            </value>
            <value>
                <fullName>Attempted</fullName>
            </value>
            <value>
                <fullName>Bad Number</fullName>
                <color>#F96FB7</color>
                <label>Bad Number</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
                <color>#2F5D85</color>
                <label>Not Interested</label>
            </value>
            <value>
                <fullName>Dupe</fullName>
                <color>#AFCADF</color>
                <label>Dupe</label>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
                <color>#EFAE73</color>
                <label>Do Not Call</label>
            </value>
            <value>
                <fullName>EF Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Status__c/Account_Status__c.object-meta.xml
<CustomObject>
    <label>Account Status</label>
    <nameField>
        <label>Account Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Skills_Sales__c.field-meta.xml
<CustomField>
    <fullName>Skills_Sales__c</fullName>
    <label>Sales Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Setter</fullName>
            </value>
            <value>
                <fullName>Closer</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Team Lead</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Corp Upsales</fullName>
            </value>
            <value>
                <fullName>Merchant</fullName>
            </value>
            <value>
                <fullName>Dissolution</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>Cross-Sale</fullName>
            </value>
            <value>
                <fullName>ClientBooksConsult</fullName>
            </value>
            <value>
                <fullName>ClientBooks Cross-Sell</fullName>
            </value>
            <value>
                <fullName>Entity Formation Sales</fullName>
            </value>
            <value>
                <fullName>Equip Sales</fullName>
            </value>
            <value>
                <fullName>Equip Setter</fullName>
            </value>
            <value>
                <fullName>Paid Digital</fullName>
            </value>
            <value>
                <fullName>CBCSched</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Calculator Override</fullName>
            </value>
            <value>
                <fullName>Digital Business Solutions</fullName>
            </value>
            <value>
                <fullName>Entity</fullName>
            </value>
            <value>
                <fullName>Paid Digital–CORE</fullName>
            </value>
            <value>
                <fullName>Paid Digital–Entity</fullName>
            </value>
            <value>
                <fullName>TSA</fullName>
            </value>
            <value>
                <fullName>Extended Hours</fullName>
            </value>
            <value>
                <fullName>TSA-Spanish</fullName>
            </value>
            <value>
                <fullName>Paid Digital-Spanish</fullName>
            </value>
            <value>
                <fullName>HRB</fullName>
            </value>
            <value>
                <fullName>Guided Selling-Setter</fullName>
            </value>
            <value>
                <fullName>Guided Selling-TSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TransferAccts.cls
global class TransferAccts implements Schedulable {
	
	global void execute(SchedulableContext SC) {
       SetTransferEligibilityonAccounts();
   }
   
    public static Set<String> NonTransferStatuses = new Set<String>{
    	'Qualified','Bad Number','Not Interested','Dupe','Dialer Call Back'};
    	
    public static Set<String> TransferAcctStatuses = new Set<String>{
    	'New','No Sale','BTP'};	    	
      
   
    public static void SetTransferEligibilityonAccounts()  {
    	List <User> users = [SELECT Id,Name,IsActive,Skills_Sales__c FROM User WHERE IsActive = TRUE];
    	User acctowner;
    	Map<ID,User> salesusermap = new Map<Id,User>();
    	for(User u :users)  {
    		if(u.Skills_Sales__c<>null && u.Skills_Sales__c.contains('Closer')) salesusermap.put(u.id,u);
    		if(u.Name == 'Brooke Van Remoortere') acctowner = u;    	
    	}
    	
    	List<Account> accts = new List<Account>([SELECT ID,Name,Ownerid,CreatedDate,LastActivityDate,Transfer_Eligible__c,Lead_Status__c FROM Account WHERE Lead_Status__c NOT IN :NonTransferStatuses AND Account_Status__c IN :TransferAcctStatuses AND Ownerid IN :salesusermap.keyset() LIMIT 50000]);
   		List<Account> acctsToUpdate = new List<Account>(); 
   		for (Account a : accts)  {
   			Date CreatedDateOnly = date.newinstance(a.CreatedDate.year(), a.CreatedDate.month(), a.CreatedDate.day());
   			if(CreatedDateOnly.daysbetween(System.Today()) > 37 && (a.LastActivityDate == null || a.LastActivityDate.daysbetween(System.Today()) > 0))  {
    			a.Transfer_Eligible__c = TRUE;
    			a.ownerid = acctowner.id;
    			acctsToUpdate.add(a);    			
    		}
   		}
    	if(!acctsToUpdate.IsEmpty()) update acctsToUpdate;    	  
    }
}