force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Active_Subscriptions__c/Active_Subscriptions__c.object-meta.xml
<CustomObject>
    <label>Active Subscription</label>
    <nameField>
        <label>Active Subscriptions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Active Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Active_Subscriptions__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Subscriptions</relationshipLabel>
    <relationshipName>Active_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Businesss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Businesses</relationshipLabel>
    <relationshipName>Businesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice__c/ChargeOver_Invoice__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Invoice</label>
    <nameField>
        <label>ChargeOver Invoice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Invoices</relationshipLabel>
    <relationshipName>ChargeOver_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/ChargeOver_Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Invoice Line Item</label>
    <nameField>
        <label>ChargeOver Invoice Items Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Invoice Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Invoice_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Invoice Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote__c/ChargeOver_Quote__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Quote</label>
    <nameField>
        <label>ChargeOver Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Quotes</relationshipLabel>
    <relationshipName>ChargeOver_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/ChargeOver_Quote_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Quote Line Item</label>
    <nameField>
        <label>ChargeOver Quote Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Quote Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Quote_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Quote Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription__c/ChargeOver_Subscription__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription</label>
    <nameField>
        <label>ChargeOver Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscriptions</relationshipLabel>
    <relationshipName>ChargeOver_Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/ChargeOver_Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Subscription Line Item</label>
    <nameField>
        <label>ChargeOver Subscription Line Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Subscription Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Subscription_Line_Item__c/fields/ChargeOver_Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ChargeOver Subscription Line Item</label>
    <referenceTo>ChargeOver_Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>ChargeOver Subscription Line Items</relationshipLabel>
    <relationshipName>ChargeOver_Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Transaction__c/ChargeOver_Transaction__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Transaction</label>
    <nameField>
        <label>ChargeOver Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChargeOver Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Transactions</relationshipLabel>
    <relationshipName>ChargeOver_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ChargeOver_Transaction_Applied__c/ChargeOver_Transaction_Applied__c.object-meta.xml
<CustomObject>
    <label>ChargeOver Transaction Applied</label>
    <nameField>
        <displayFormat>TA-{000000}</displayFormat>
        <label>Transaction Applied Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ChargeOver Transactions Applied</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChargeOver_Transaction_Applied__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>ChargeOver Transactions Applied</relationshipLabel>
    <relationshipName>ChargeOver_Transactions_Applied</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GetFeedback_Survey_Response__c/GetFeedback_Survey_Response__c.object-meta.xml
<CustomObject>
    <label>GetFeedback Survey Response</label>
    <nameField>
        <label>GetFeedback Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GetFeedback Survey Responses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GetFeedback_Survey_Response__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GetFeedback Survey Responses</relationshipLabel>
    <relationshipName>GetFeedback_Survey_Responses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Plan_Surveys__c/Legal_Plan_Surveys__c.object-meta.xml
<CustomObject>
    <label>Legal Plan Surveys</label>
    <nameField>
        <label>Legal Plan Surveys  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Plan Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Plan_Surveys__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Legal Plan Surveys</relationshipLabel>
    <relationshipName>Legal_Plan_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_GetFeedback_Surveys__c/Sales_GetFeedback_Surveys__c.object-meta.xml
<CustomObject>
    <label>Sales GetFeedback Survey</label>
    <nameField>
        <label>Sales GetFeedback Surveys Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales GetFeedback Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_GetFeedback_Surveys__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales GetFeedback Surveys</relationshipLabel>
    <relationshipName>Sales_GetFeedback_Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shareholder__c/Shareholder__c.object-meta.xml
<CustomObject>
    <label>Shareholder</label>
    <nameField>
        <label>Shareholder Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shareholders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shareholder__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shareholders</relationshipLabel>
    <relationshipName>Shareholders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SMS_Schedule__c/SMS_Schedule__c.object-meta.xml
<CustomObject>
    <label>SMS Schedule</label>
    <nameField>
        <label>SMS Schedule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMS Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SMS_Schedule__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SMS Schedules</relationshipLabel>
    <relationshipName>SMS_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountDeleteRelatedRecords.cls
public class AccountDeleteRelatedRecords {
    private List<Id> accountIds;
    public AccountDeleteRelatedRecords(List<Id> accountIds){this.accountIds = accountIds;}
    public void deleteRelatedRecords() {
        //Each list can only hold 10 different object types so if you have more than 10 you need to make another list
        List<SObject> relatedRecordsToDelete = new List<SObject>();
        List<SObject> relatedRecordsToDelete2 = new List<SObject>();
        List<SObject> relatedRecordsToDelete3 = new List<SObject>();

        //10
        relatedRecordsToDelete.addAll(this.deleteRecords('ChargeOver_Subscription_Line_Item__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('ChargeOver_Quote_Line_Item__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('Active_Subscriptions__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('GetFeedback_Survey_Response__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('Sales_GetFeedback_Surveys__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('Legal_Plan_Surveys__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('Survey__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('SMS_Schedule__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('ChargeOver_Invoice__c', 'Account__c'));
        relatedRecordsToDelete.addAll(this.deleteRecords('ChargeOver_Invoice_Line_Item__c', 'Account__c'));
        //20
        relatedRecordsToDelete2.addAll(this.deleteRecords('ChargeOver_Quote__c', 'Account__c'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('ChargeOver_Subscription__c', 'Account__c'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('ChargeOver_Transaction__c', 'Account__c'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('ChargeOver_Transaction_Applied__c', 'Account__c'));
        relatedRecordsToDelete3.addAll(this.deleteRecords('Bill62__Payment_Method__c', 'Bill62__Account__c '));
        relatedRecordsToDelete3.addAll(this.deleteRecords('Bill62__Payment__c', 'Bill62__Account__c '));
        relatedRecordsToDelete3.addAll(this.deleteRecords('Bill62__Subscription__c', 'Bill62__Account__c '));
        relatedRecordsToDelete3.addAll(this.deleteRecords('Bill62__Order__c', 'Bill62__Account__c'));
        relatedRecordsToDelete3.addAll(this.deleteRecords('Business__c', 'Account__c'));
        relatedRecordsToDelete3.addAll(this.deleteRecords('Shareholder__c', 'Account__c'));
        //30  
        relatedRecordsToDelete3.addAll(this.deleteRecords('X1099_Form__c', 'Payee_Account__c'));      
        relatedRecordsToDelete2.addAll(this.deleteRecords('Case', 'AccountId'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('Event', 'WhatId'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('Task', 'WhatId'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('Contact', 'AccountId'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('Opportunity', 'AccountId'));
        relatedRecordsToDelete2.addAll(this.deleteRecords('Lead', 'ConvertedAccountId'));
        /* Instructions on adding additional objects to delete: 
        *  Use the following code snippet but replace the parameters, then add it in below
        *  relatedRecordsToDelete3.addAll(this.deleteRecords('X1099_Form__c', 'Payee_Account__c'));
        *  1st Parameter: Object's API name eg Business__c
        *  2nd Parameter: The name of the field on the object that relates it to account eg Account__c
        *  Note: If you are adding more than 10 types of objects to a list you need to make a new one
        */

        delete relatedRecordsToDelete;
        delete relatedRecordsToDelete2;
        delete relatedRecordsToDelete3;

    }

    private List<sObject> deleteRecords(String objectToDelete, String relationshipName){
        String queryString = 'SELECT Id FROM '+objectToDelete+' WHERE '+relationshipName+' IN :accountIds';
        return Database.query(queryString);
    }
}