force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>1st Year Client</fullName>
            </value>
            <value>
                <fullName>Renewed Client</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
            <value>
                <fullName>Active-Pending Cancel (Pause)</fullName>
            </value>
            <value>
                <fullName>Paused Client</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Business Account</fullName>
            </value>
            <value>
                <fullName>Partner Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/ChargeOver_Most_Recent_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Most_Recent_Payment_Date__c</fullName>
    <description>The Transaction Date of the most recent ChargeOver Payment Transaction related to the Account</description>
    <label>ChargeOver Most Recent Payment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Finance_Status__c.field-meta.xml
<CustomField>
    <fullName>Finance_Status__c</fullName>
    <label>Finance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Paused</fullName>
            </value>
            <value>
                <fullName>Refunded</fullName>
            </value>
            <value>
                <fullName>Blacklisted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <isActive>false</isActive>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Status__c/Account_Status__c.object-meta.xml
<CustomObject>
    <label>Account Status</label>
    <nameField>
        <label>Account Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DormantAccountStatusBatch.cls
public class DormantAccountStatusBatch implements Database.Batchable<sObject>, Schedulable {
    public Date fifteenMonthsAgo;
    public String batchQuery = 
          'SELECT Id, Name, Account_Status__c, ChargeOver_Most_Recent_Payment_Date__c, Finance_Status__c '
        + 'FROM Account '
        + 'WHERE ChargeOver_Most_Recent_Payment_Date__c < :fifteenMonthsAgo '
        + 'AND Finance_Status__c != \'Dormant\' ';

    public DormantAccountStatusBatch() { 
        this.fifteenMonthsAgo = Date.today().addMonths(-15);
    }
    public Database.QueryLocator start(Database.BatchableContext bc)  {
        return Database.getQueryLocator(batchQuery);
    }
    public void execute(SchedulableContext context) {
        DormantAccountStatusBatch assignStatus = new DormantAccountStatusBatch();
        Database.executeBatch(assignStatus, 1);
    }
    public void execute(Database.BatchableContext bc, List<Account> accounts){
        this.execute(accounts);
    }
    public void execute(List<Account> accounts) {
        List<Id> accountIds = new List<Id>();
        for(Account a : accounts){
            accountIds.add(a.Id);
        }
        AccountStatusHandler.assignAccountStatus(accountIds);
    }

    public void finish(Database.BatchableContext bc){}    
}