force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payroll_Accountant__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Accountant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payroll Accountant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Product__c/Account_Product__c.object-meta.xml
<CustomObject>
    <label>Account Product</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Account Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Product__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Products</relationshipLabel>
    <relationshipName>Account_Products</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Product__c/fields/Interval__c.field-meta.xml
<CustomField>
    <fullName>Interval__c</fullName>
    <label>Interval</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>15th / 30th</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Product__c/fields/Payroll_Accountant__c.field-meta.xml
<CustomField>
    <fullName>Payroll_Accountant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payroll Accountant</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Account_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreatePayrollDatesControllerTest.cls
@isTest private class CreatePayrollDatesControllerTest {
    
    @testSetup static void CreateTestData(){
        Account a = new Account();
        a.Name = 'Test Account';
        insert a;
        
        Account_Product__c ap = new Account_Product__c();
        ap.Account__c = a.Id;
        ap.Payroll_Accountant__c = UserInfo.getUserId();
        ap.Start_Date__c = date.newInstance(2015, 7, 7);
        ap.Interval__c = 'Monthly';
        insert ap;        
    }
    
    static testMethod void CreatePayrollDates(){
        Account a = [Select Id from Account LIMIT 1];
        Account_Product__c ap = [Select Id, Account__c from Account_Product__c where Account__c = :a.Id LIMIT 1];
        CreatePayrollDatesController cpd = new CreatePayrollDatesController(new ApexPages.StandardController(ap));
        cpd.CreatePayrollDates();
    }
}