force-app/main/default/objects/Account/fields/Bill62__Active__c.field-meta.xml
<CustomField>
    <fullName>Bill62__Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
                <color>#78C953</color>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>Call Back Set</fullName>
                <color>#E27001</color>
                <label>Call Back Set</label>
            </value>
            <value>
                <fullName>1-1 Request</fullName>
                <color>#66E9BD</color>
                <label>1-1 Request</label>
            </value>
            <value>
                <fullName>1-1 No Show</fullName>
                <color>#0B24BE</color>
                <label>1-1 No Show</label>
            </value>
            <value>
                <fullName>1-1 Cancelled</fullName>
                <color>#419249</color>
                <label>1-1 Cancelled</label>
            </value>
            <value>
                <fullName>Pitched</fullName>
                <color>#B6E32E</color>
                <label>Pitched</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <color>#641CCF</color>
                <label>Qualified</label>
            </value>
            <value>
                <fullName>Attempted</fullName>
            </value>
            <value>
                <fullName>Bad Number</fullName>
                <color>#F96FB7</color>
                <label>Bad Number</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
                <color>#2F5D85</color>
                <label>Not Interested</label>
            </value>
            <value>
                <fullName>Dupe</fullName>
                <color>#AFCADF</color>
                <label>Dupe</label>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
                <color>#EFAE73</color>
                <label>Do Not Call</label>
            </value>
            <value>
                <fullName>EF Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Product_Settings__c/Account_Product_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Account Product Settings</label>
</CustomObject>

force-app/main/default/objects/Account_Product_Settings__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Categories__c.field-meta.xml
<CustomField>
    <fullName>Product_Categories__c</fullName>
    <label>Product Categories</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tax Consulting</fullName>
            </value>
            <value>
                <fullName>Business Tax Prep</fullName>
            </value>
            <value>
                <fullName>Personal Tax Prep</fullName>
            </value>
            <value>
                <fullName>Client Books</fullName>
            </value>
            <value>
                <fullName>Full-Service Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Estimated Taxes</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Sales and Use Tax</fullName>
            </value>
            <value>
                <fullName>Two-Year Review</fullName>
            </value>
            <value>
                <fullName>UTC</fullName>
            </value>
            <value>
                <fullName>Personal Tax Return</fullName>
            </value>
            <value>
                <fullName>Audit Support</fullName>
            </value>
            <value>
                <fullName>Registered Agent</fullName>
            </value>
            <value>
                <fullName>CORP</fullName>
            </value>
            <value>
                <fullName>Business Plan</fullName>
            </value>
            <value>
                <fullName>VTO</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Dissolution</fullName>
            </value>
            <value>
                <fullName>Financial Affidavit</fullName>
            </value>
            <value>
                <fullName>Mobile Merchant Processing</fullName>
            </value>
            <value>
                <fullName>Deluxe Recordkeeping Package</fullName>
            </value>
            <value>
                <fullName>Tax Extension</fullName>
            </value>
            <value>
                <fullName>Amended Return (2014)</fullName>
            </value>
            <value>
                <fullName>Revenue Clearance</fullName>
            </value>
            <value>
                <fullName>Final Tax Return</fullName>
            </value>
            <value>
                <fullName>2014 Business Tax Prep</fullName>
            </value>
            <value>
                <fullName>Additional Personal Return</fullName>
            </value>
            <value>
                <fullName>Additional Storage</fullName>
            </value>
            <value>
                <fullName>Articles of Dissolution</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Business Document</fullName>
            </value>
            <value>
                <fullName>Business Document Center</fullName>
            </value>
            <value>
                <fullName>Business Plan</fullName>
            </value>
            <value>
                <fullName>DO NOT PAY</fullName>
            </value>
            <value>
                <fullName>Entity Set Up and Binder</fullName>
            </value>
            <value>
                <fullName>Payroll</fullName>
            </value>
            <value>
                <fullName>Tax Membership</fullName>
            </value>
            <value>
                <fullName>Tax Preparation</fullName>
            </value>
            <value>
                <fullName>Complete Accounting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <inlineHelpText>This field indicates what order the product will appear on a ChargeOver invoice. If 1, then all of the other product descriptions will display on a single product, if 2 or greater that will affect the other sort orders.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Update_Account_Owner_Helper.cls
public class Update_Account_Owner_Helper {
	
	public static boolean checkActiveProduct(Id accountId){
		
		boolean isActiveProduct = false;

		List<String> listProductCategories = new List<String>();
		Set<String> setActiveCategories = new Set<String>();

		// Get Product Categories list from schema
		Schema.sObjectType objType = Product2.getSObjectType(); 
		Schema.DescribeSObjectResult objDescribe = objType.getDescribe();       
		map<String, Schema.SObjectField> fieldMap = objDescribe.fields.getMap(); 
		List<Schema.PicklistEntry> values = fieldMap.get('Product_Categories__c').getDescribe().getPickListValues();
		
		for(Schema.PicklistEntry v: values){
			listProductCategories.add(v.getValue());  
		}

		List<Bill62__Subscription__c> listActiveSubs = [Select Id
															, Bill62__Account__c
															, Bill62__Product__c
															, Bill62__Active__c 
															, Bill62__Suspended__c
															, Bill62__Termination_Date__c
															, Bill62__End_Date__c
															from Bill62__Subscription__c 
															where Bill62__Account__c = :accountId
															and Bill62__Active__c = true
															and Bill62__Suspended__c = false
															and (Bill62__Termination_Date__c > today or Bill62__Termination_Date__c = null)
															and (Bill62__End_Date__c > today or Bill62__End_Date__c = null)
														];


		if(listActiveSubs.size() > 0){

			Set<Id> setActiveProductIds = new Set<Id>();
			
			for(Bill62__Subscription__c s : listActiveSubs){
				setActiveProductIds.add(s.Bill62__Product__c);
			}

			//List<Product2> listActiveProducts = [Select Id, Name, Product_Categories__c from Product2 where Id IN :setActiveProductIds];

			for(Product2 p : [Select Id, Name, Product_Categories__c from Product2 where Id IN :setActiveProductIds]){
				if(p.Product_Categories__c == null){
					continue;
				}
				List<String> myCategories = p.Product_Categories__c.split(';');
				List<String> selectedCategories = new List<String>();               

				// Create list from all categories, flagging which ones are on product and which ones aren't
				for(String c : listProductCategories){  
					for(String m : myCategories){
						if(c == m){
							selectedCategories.add(m);
						}
					}
				}

			//setActiveCategories.addAll(selectedCategories);
			}

			if(setActiveCategories.size() > 0){
				isActiveProduct = Update_Account_Owner_Helper.sortCategories(setActiveCategories);
			} else {
				isActiveProduct = false;
			}

		}

		System.debug('isActiveProduct:-->' + isActiveProduct);
		
		return isActiveProduct;
	}

	public Static boolean sortCategories(Set<String> setCats){

		boolean isActive = false;
		String categories = '';

		List<Account_Product_Settings__c> customSettings = [SELECT Product_Category__c FROM Account_Product_Settings__c
		ORDER BY Sort_Order__c ASC];

		for(Account_Product_Settings__c aps: customSettings){
			if(setCats.contains(aps.Product_Category__c)){
				isActive = true;
				break;
			}
		}

		return isActive;
	}

	public static boolean checkPitchedAccount(Account acct){
		Integer taskCount = [Select count() from Task where WhatId =: acct.Id and Subject like '%Sales Follow Up%' and ActivityDate > TODAY];
		Integer eventCount = [Select count() from Event where WhatId =: acct.Id and Subject like '%Sales Follow Up%' and ActivityDate > TODAY];

		if(taskCount > 0 || eventCount > 0) {

			List<AccountHistory> lstAccountHistory = [SELECT AccountId, Field, Id, NewValue, OldValue, CreatedDate FROM AccountHistory Where Field='Lead_Status__c' and AccountId =: acct.Id and CreatedDate < N_DAYS_AGO:28 Order By CreatedDate desc Limit 1];

			if(lstAccountHistory.size() > 0) {
				if(lstAccountHistory[0].NewValue == acct.Lead_Status__c)
					return true;
			}

		} else {

			List<AccountHistory> lstAccountHistory = [SELECT AccountId, Field, Id, NewValue, OldValue, CreatedDate FROM AccountHistory Where Field='Lead_Status__c' and AccountId =: acct.Id and CreatedDate < N_DAYS_AGO:14 Order By CreatedDate desc Limit 1];			

			if(lstAccountHistory.size() > 0) {
				if(lstAccountHistory[0].NewValue == acct.Lead_Status__c)
					return true;
			}

		}
		return false;
	}
}