force-app/main/default/objects/Account/fields/ChargeOver_Initial_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Initial_Payment_Date__c</fullName>
    <description>The Transaction Date of the earliest ChargeOver Transaction related to the Account</description>
    <label>ChargeOver Initial Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Distribute_Date__c.field-meta.xml
<CustomField>
    <fullName>Distribute_Date__c</fullName>
    <label>Distribute Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Type_New__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type_New__c</fullName>
    <label>Lead Type New</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1800Accountant App</fullName>
            </value>
            <value>
                <fullName>1800Acct EIN</fullName>
            </value>
            <value>
                <fullName>1800Acct Homepage</fullName>
            </value>
            <value>
                <fullName>1800Acct MobileHome</fullName>
            </value>
            <value>
                <fullName>Abandoner</fullName>
            </value>
            <value>
                <fullName>Abandoner Non-Buyers</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Agent Referral</fullName>
            </value>
            <value>
                <fullName>App Download</fullName>
            </value>
            <value>
                <fullName>ASAP Lead</fullName>
            </value>
            <value>
                <fullName>Back to Business</fullName>
            </value>
            <value>
                <fullName>BAP</fullName>
            </value>
            <value>
                <fullName>BA - UA</fullName>
            </value>
            <value>
                <fullName>Blog Join Now</fullName>
            </value>
            <value>
                <fullName>Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Opt In</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Services</fullName>
            </value>
            <value>
                <fullName>BPlans Referral</fullName>
            </value>
            <value>
                <fullName>BTP</fullName>
            </value>
            <value>
                <fullName>BTP, LP, and BTOI</fullName>
            </value>
            <value>
                <fullName>BTP, LP, and STF</fullName>
            </value>
            <value>
                <fullName>BTP, LP, STF, and BTOI</fullName>
            </value>
            <value>
                <fullName>BTP and Business LP</fullName>
            </value>
            <value>
                <fullName>BTP and Buyer Tax Opt In</fullName>
            </value>
            <value>
                <fullName>BTP and STF</fullName>
            </value>
            <value>
                <fullName>BTP-Standalone</fullName>
            </value>
            <value>
                <fullName>Business Accounting</fullName>
            </value>
            <value>
                <fullName>Business LP</fullName>
            </value>
            <value>
                <fullName>Buyer Tax Opt In</fullName>
            </value>
            <value>
                <fullName>LegalZoom</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Pitched_Date__c.field-meta.xml
<CustomField>
    <fullName>Pitched_Date__c</fullName>
    <label>Consulted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Distribute_Date__c.field-meta.xml
<CustomField>
    <fullName>Distribute_Date__c</fullName>
    <formula>Account.Distribute_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distribute Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/of_Pre_TSA_Calls__c.field-meta.xml
<CustomField>
    <fullName>of_Pre_TSA_Calls__c</fullName>
    <description>The number of logged phone calls made prior to a held TSA appointment</description>
    <inlineHelpText>The number of logged phone calls made prior to a held TSA appointment</inlineHelpText>
    <label># of Pre-TSA Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/of_TSA_Follow_Up_Calls__c.field-meta.xml
<CustomField>
    <fullName>of_TSA_Follow_Up_Calls__c</fullName>
    <description>The number of logged phone calls made after a held TSA appointment, but before the first sale</description>
    <inlineHelpText>The number of logged phone calls made after a held TSA appointment, but before the first sale</inlineHelpText>
    <label># of TSA Follow-Up Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Type_New__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type_New__c</fullName>
    <description>New multi-select picklist for tracking multiple lead types</description>
    <label>Lead Type New</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1-800Accountant</fullName>
            </value>
            <value>
                <fullName>1800Accountant App</fullName>
            </value>
            <value>
                <fullName>1-800Accountant Registration</fullName>
            </value>
            <value>
                <fullName>1800Acct EIN</fullName>
            </value>
            <value>
                <fullName>1800Acct Homepage</fullName>
            </value>
            <value>
                <fullName>1800Acct MobileHome</fullName>
            </value>
            <value>
                <fullName>1800 BTP</fullName>
            </value>
            <value>
                <fullName>Abandoner</fullName>
            </value>
            <value>
                <fullName>Abandoner Non-Buyers</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting (Business)</fullName>
            </value>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Agent Referral</fullName>
            </value>
            <value>
                <fullName>App Download</fullName>
            </value>
            <value>
                <fullName>April Newsletter</fullName>
            </value>
            <value>
                <fullName>ASAP Lead</fullName>
            </value>
            <value>
                <fullName>Back to Business</fullName>
            </value>
            <value>
                <fullName>banking_purposes</fullName>
            </value>
            <value>
                <fullName>BAP</fullName>
            </value>
            <value>
                <fullName>BA - UA</fullName>
            </value>
            <value>
                <fullName>Blog Join Now</fullName>
            </value>
            <value>
                <fullName>Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Opt In</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Services</fullName>
            </value>
            <value>
                <fullName>BPlans Partner Page Referral</fullName>
            </value>
            <value>
                <fullName>BPlans Referral</fullName>
            </value>
            <value>
                <fullName>BTP</fullName>
            </value>
            <value>
                <fullName>BTP, Business LP</fullName>
            </value>
            <value>
                <fullName>BTP, Business LP, Buyer Tax Opt In</fullName>
            </value>
            <value>
                <fullName>Buyer Tax Opt In</fullName>
            </value>
            <value>
                <fullName>LegalZoom</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/of_TSA_Follow_Up_Calls__c.field-meta.xml
<CustomField>
    <fullName>of_TSA_Follow_Up_Calls__c</fullName>
    <label># of TSA Follow-Up Calls</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Pitched_Date__c.field-meta.xml
<CustomField>
    <fullName>Pitched_Date__c</fullName>
    <description>To track date/time of pitch</description>
    <label>Consulted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TaskTriggerHandlerTest.cls
@IsTest
public with sharing class TaskTriggerHandlerTest {
    @TestSetup
    private static void testDataSetup() {
        Account acc = new Account(Name='test account',
        Distribute_Date__c=Date.today(), Pitched_Date__c = Date.today().addDays(2),
        ChargeOver_Initial_Payment_Date__c=Date.today().addDays(4));
        insert acc;
        Contact con = new Contact(FirstName='Test', LastName='contact', AccountId=acc.Id);
        insert con;

        Lead l = new Lead(Distribute_Date__c=Date.today(), Pitched_Date__c = Date.today().addDays(2),
        LeadSource='LegalZoom', Status='New', Lead_Type_New__c='Buyer Tax Opt In', FirstName='first',
        LastName='last', Company='company');
        insert l;
    }

    @IsTest
    public static void insertLeadCalls(){
        Lead l = [SELECT Id, Distribute_Date__c, Pitched_Date__c FROM Lead LIMIT 1];
        Integer count = 5;
        List<Task> newTasks = new List<Task>();
        User owner = [SELECT Id FROM User WHERE Name='Matthew Clark' LIMIT 1];
        for(Integer i=0; i<count; i++){
            newTasks.add(new Task(
                Subject='test task',
                OwnerId=owner.Id,
                ActivityDate=Date.today(),
                NVMContactWorld__CW_Call_Start_Time__c = Datetime.now(),
                WhoId = l.Id,
                CallType='Outbound',
                CallDurationInSeconds=5
            ));
        }
        System.debug(newTasks);
        Test.startTest();
        insert newTasks;
        Test.stopTest();
        l = [SELECT Id, of_Pre_TSA_Calls__c FROM Lead LIMIT 1];
        System.debug(l.of_Pre_TSA_Calls__c);
        System.assert(l.of_Pre_TSA_Calls__c == count);
    }

    @IsTest
    public static void insertContactCalls(){
        Contact con = [SELECT Id FROM Contact LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Integer preCount = 3;
        Integer postCount = 4;
        List<Task> newTasks = new List<Task>();
        User owner = [SELECT Id FROM User WHERE Name='Matthew Clark' LIMIT 1];
        for(Integer i=0; i<preCount; i++){
            newTasks.add(new Task(
                Subject='test task',
                OwnerId=owner.Id,
                ActivityDate=Date.today(),
                NVMContactWorld__CW_Call_Start_Time__c = Datetime.now(),
                WhoId = con.Id,
                WhatId = acc.Id,
                CallType='Outbound',
                CallDurationInSeconds=5
            ));
        }
        for(Integer i=0; i<postCount; i++){
            newTasks.add(new Task(
                Subject='test task',
                OwnerId=owner.Id,
                ActivityDate=Date.today().addDays(3),
                NVMContactWorld__CW_Call_Start_Time__c = Datetime.now().addDays(3),
                WhoId = con.Id,
                WhatId = acc.Id,
                CallType='Outbound',
                CallDurationInSeconds=5
            ));
        }
        System.debug(newTasks);
        Test.startTest();
        insert newTasks;
        Test.stopTest();
        con = [SELECT Id, of_Pre_TSA_Calls__c, of_TSA_Follow_Up_Calls__c FROM Contact LIMIT 1];
        acc = [SELECT Id, of_Pre_TSA_Calls__c, of_TSA_Follow_Up_Calls__c FROM Account LIMIT 1];
        System.debug(con);
        System.debug(acc);
        System.assertEquals(con.of_Pre_TSA_Calls__c, preCount);
        System.assertEquals(acc.of_Pre_TSA_Calls__c, preCount);
        //System.assertEquals(con.of_TSA_Follow_Up_Calls__c, postCount);
        //System.assertEquals(acc.of_TSA_Follow_Up_Calls__c, postCount);
    }

}