force-app/main/default/objects/Account/fields/Current_Year_Profit_Projection__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Profit_Projection__c</fullName>
    <description>Client Information</description>
    <label>Current Year Profit Projection</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>At a loss</fullName>
            </value>
            <value>
                <fullName>$0-$25,000</fullName>
            </value>
            <value>
                <fullName>$25,001-$50,000</fullName>
            </value>
            <value>
                <fullName>$50,001-$100,000</fullName>
            </value>
            <value>
                <fullName>$100,001+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <label>$0</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <label>$5,000</label>
            </value>
            <value>
                <fullName>10000</fullName>
                <label>$10,000</label>
            </value>
            <value>
                <fullName>25000</fullName>
                <label>$25,000</label>
            </value>
            <value>
                <fullName>50000</fullName>
                <label>$50,000</label>
            </value>
            <value>
                <fullName>75000</fullName>
                <label>$75,000</label>
            </value>
            <value>
                <fullName>100000</fullName>
                <label>$100,000</label>
            </value>
            <value>
                <fullName>150000</fullName>
                <label>$150,000</label>
            </value>
            <value>
                <fullName>250000</fullName>
                <label>$250,000</label>
            </value>
            <value>
                <fullName>500000</fullName>
                <label>$500,000</label>
            </value>
            <value>
                <fullName>1000000</fullName>
                <label>$1,000,000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Potential_Total_Savings__c.field-meta.xml
<CustomField>
    <fullName>Potential_Total_Savings__c</fullName>
    <label>Potential Total Savings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChargeOver_Quote_URL__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Quote_URL__c</fullName>
    <label>ChargeOver Quote URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Post_TSA_Link__c.field-meta.xml
<CustomField>
    <fullName>Post_TSA_Link__c</fullName>
    <label>Post TSA Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/EventPostTsaEmailBatchTest.cls
/**
*   Overview: Test class for EventPostTsaEmailBatch
*   Author: Koby Campbell
*   Date: June 2021
*/

@IsTest
private class EventPostTsaEmailBatchTest{
    @IsTest
    private static void testEmailSent() {
        Test.startTest();
        EventPostTsaEmailBatch batchJob = new EventPostTsaEmailBatch();
        Database.executeBatch(batchJob, 1);
        Test.stopTest();

        Opportunity testOpportunity = [
            SELECT Id, Name, Post_TSA_Link__c
            FROM Opportunity
            WHERE Name = 'Post TSA Test'
            LIMIT 1
        ];

        //System.assertNotEquals(null, testOpportunity.Post_TSA_Link__c);
    }

    @TestSetup
    private static void testSetup() {

        //Match all criteria for email to go out and link to be generated
        Account account = TestDataGenerator.createTestAccountWithoutOwner();
        account.Current_Year_Profit_Projection__c = '50000';
        account.Potential_Total_Savings__c = '$12,321';
        insert account;

        Contact contact = TestDataGenerator.createTestContact(account);
        contact.email = 'test@test.com';
        insert contact;

        account.Primary_Contact__c = contact.Id;
        update account;

        Opportunity opportunity = TestDataGenerator.createTestOpportunity(account);
        opportunity.ChargeOver_Quote_URL__c = 'www.test.com';
        opportunity.Name = 'Post TSA Test';
        insert opportunity;

        Event event = TestDataGenerator.createTestEvent();
        event.WhatId = opportunity.Id;
        event.ActivityDateTime  = Datetime.now().addDays(-2);
        event.StartDateTime = event.ActivityDateTime;
        event.EndDateTime = Datetime.now().addDays(-2).addMinutes(30);
        event.Subject = '1on1 Sales Appointment';
        event.Type_of_Appointment__c = 'Tax Savings Analysis';
        event.Appointment_Disposition__c = 'Consulted';
        event.Secondary_Disposition_Details__c = 'Not Interested';
        System.debug(event.ActivityDateTime);
        System.debug(event.StartDateTime);

        
        insert event;
    }
}