force-app/main/default/objects/Account/fields/Current_Year_Profit_Projection__c.field-meta.xml
<CustomField>
    <fullName>Current_Year_Profit_Projection__c</fullName>
    <description>Client Information</description>
    <label>Current Year Profit Projection</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>At a loss</fullName>
            </value>
            <value>
                <fullName>$0-$25,000</fullName>
            </value>
            <value>
                <fullName>$25,001-$50,000</fullName>
            </value>
            <value>
                <fullName>$50,001-$100,000</fullName>
            </value>
            <value>
                <fullName>$100,001+</fullName>
            </value>
            <value>
                <fullName>0</fullName>
                <label>$0</label>
            </value>
            <value>
                <fullName>5000</fullName>
                <label>$5,000</label>
            </value>
            <value>
                <fullName>10000</fullName>
                <label>$10,000</label>
            </value>
            <value>
                <fullName>25000</fullName>
                <label>$25,000</label>
            </value>
            <value>
                <fullName>50000</fullName>
                <label>$50,000</label>
            </value>
            <value>
                <fullName>75000</fullName>
                <label>$75,000</label>
            </value>
            <value>
                <fullName>100000</fullName>
                <label>$100,000</label>
            </value>
            <value>
                <fullName>150000</fullName>
                <label>$150,000</label>
            </value>
            <value>
                <fullName>250000</fullName>
                <label>$250,000</label>
            </value>
            <value>
                <fullName>500000</fullName>
                <label>$500,000</label>
            </value>
            <value>
                <fullName>1000000</fullName>
                <label>$1,000,000</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Potential_Total_Savings__c.field-meta.xml
<CustomField>
    <fullName>Potential_Total_Savings__c</fullName>
    <label>Potential Total Savings</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Primary Contact)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ChargeOver_Quote_URL__c.field-meta.xml
<CustomField>
    <fullName>ChargeOver_Quote_URL__c</fullName>
    <label>ChargeOver Quote URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Post_TSA_Link__c.field-meta.xml
<CustomField>
    <fullName>Post_TSA_Link__c</fullName>
    <label>Post TSA Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/EventPostTsaEmailBatch.cls
/**
* Author: Koby Campbell
* Date: July 2021
* Test: EventPostTsaEmailBatchTest
*/
global class EventPostTsaEmailBatch implements Database.Batchable<sObject>, Schedulable {
    
    public EventPostTsaEmailBatch() { 
        this.aTimeAgo = Date.Today().addDays(-2);
        setQueryString();
    }
    private Date aTimeAgo;
    private String eventQuery;
    private void setQueryString(){   
        this.eventQuery = 
            'SELECT Id, WhatId, Subject, Type_of_Appointment__c, Appointment_Disposition__c, Secondary_Disposition_Details__c,  ' 
            +'TYPEOF What ' 
            +'WHEN Opportunity '
            +'THEN ChargeOver_Quote_URL__c, Post_TSA_Link__c, AccountId, Account.Potential_Total_Savings__c, Account.Current_Year_Profit_Projection__c, Account.Primary_Contact__c, Account.Id, Account.Primary_Contact_Email__c, Account.Owner.Email, Account.Owner.Name ' 
            +'END ' 
            +'FROM Event ' 
            +'WHERE DAY_ONLY(StartDateTime) = :aTimeAgo '
            +'AND What.Type = \'Opportunity\' ' 
            +'AND Secondary_Disposition_Details__c != \'Sale\' '
            +'AND Secondary_Disposition_Details__c != \'Cancelled\' ' 
            +'AND Subject LIKE \'%1on1%\' ' 
            +'AND Type_of_Appointment__c = \'Tax Savings Analysis\' '
            +'AND Appointment_Disposition__c = \'Consulted\' ' 
        ;
    }
 
    private List<Event> events;
    public void setEvents(List<Event> events) { this.events = events; }
    public void setEvents() {
        this.events = Database.query(this.eventQuery);
    }

    //Execute with a batch size of 1
    public void execute(SchedulableContext context) {
        EventPostTsaEmailBatch sendPostTsaEmail = new EventPostTsaEmailBatch();
        Database.executeBatch(sendPostTsaEmail, 1);
    }

    public Database.QueryLocator start(Database.BatchableContext context) {   

        return Database.getQueryLocator(this.eventQuery);    
    }    

    public void execute(Database.BatchableContext context, List<Event> events) {
        this.setEvents(events);
        this.manualExecution();
    }

    public void manualExecution() {   
        EmailTemplate emailTemplate = [
            SELECT Id, Subject, Description, HtmlValue, DeveloperName, Body 
            FROM EmailTemplate 
            WHERE name = 'Tax savings breakdown'
        ];

        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();
        for(Event e : events){
            //Get the Opportunity associated to the Event
            Opportunity o = e.What;
            //As long as we have a quote, potential savings, and a profit projection, send the email
            if(null != o.ChargeOver_Quote_URL__c &&
            null != o.Account.Potential_Total_Savings__c &&
            '$0' != o.Account.Potential_Total_Savings__c &&
            null != o.Account.Current_Year_Profit_Projection__c &&
            '0' != o.Account.Current_Year_Profit_Projection__c &&
            null == o.Post_TSA_Link__c){
                //Related to the Event's Opportunity's Account's Contact
                Messaging.SingleEmailMessage message = Messaging.renderStoredEmailTemplate(emailTemplate.Id, o.Account.Primary_Contact__c, o.Account.Id);
                //Replace the part of the link with the Event Id
                message.setHtmlBody(message.getHtmlBody().replace('eventIdFromCustomer', e.Id));
                //Have to set the subject manually because the body is
                message.setSubject('Thanks again! Tax savings breakdown');
                message.toAddresses = new String[] { o.Account.Primary_Contact_Email__c};
                message.optOutPolicy = 'FILTER';
                //If owned by a queue or null, give default values
                if('General Lead Queue' == o.Account.Owner.Name
                || 'Dead Leads Queue' == o.Account.Owner.Name
                || null == o.Account.Owner.Name){
                    message.setSenderDisplayName('Taylor Covey');
                    message.setReplyTo('1on1@1800accountant.com');
                    message.setHtmlBody(message.getHtmlBody().replace('General Lead Queue', 'Taylor Covey'));
                } else {
                    message.setSenderDisplayName(o.Account.Owner.Name);
                    message.setReplyTo(o.Account.Owner.Email);
                }
                //Send email and save Link to the Opportunity
                if(!Test.isRunningTest()){
                    Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{message});
                }
                o.Post_TSA_Link__c = 'https://1800accountant.secure.force.com/PostTSA1/?id='+e.Id;
                opportunitiesToUpdate.add(o);
            }
        }
        if(!opportunitiesToUpdate.isEmpty()){
            update opportunitiesToUpdate;
        }
    }


    public void finish(Database.BatchableContext context) {

        
    } 
}