force-app/main/default/objects/Account/fields/Distribute_Date__c.field-meta.xml
<CustomField>
    <fullName>Distribute_Date__c</fullName>
    <label>Distribute Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1-800Accountant</fullName>
            </value>
            <value>
                <fullName>1800Accountant-Legacy</fullName>
            </value>
            <value>
                <fullName>1-800-Company</fullName>
            </value>
            <value>
                <fullName>1800Corp.com</fullName>
            </value>
            <value>
                <fullName>Agents and Corporations</fullName>
            </value>
            <value>
                <fullName>All Florida Business Solutions</fullName>
            </value>
            <value>
                <fullName>Archetype</fullName>
            </value>
            <value>
                <fullName>Bambee</fullName>
            </value>
            <value>
                <fullName>Bark</fullName>
            </value>
            <value>
                <fullName>Betterfin</fullName>
            </value>
            <value>
                <fullName>BetterLegal</fullName>
            </value>
            <value>
                <fullName>Big Commerce</fullName>
            </value>
            <value>
                <fullName>BizCounsel</fullName>
            </value>
            <value>
                <fullName>BizFilings</fullName>
            </value>
            <value>
                <fullName>BK Search</fullName>
            </value>
            <value>
                <fullName>Bluehost</fullName>
            </value>
            <value>
                <fullName>BPAS</fullName>
            </value>
            <value>
                <fullName>Building Trades</fullName>
            </value>
            <value>
                <fullName>Business.com</fullName>
            </value>
            <value>
                <fullName>Business Licenses</fullName>
            </value>
            <value>
                <fullName>Business Talent Group</fullName>
            </value>
            <value>
                <fullName>Cartinsight</fullName>
            </value>
            <value>
                <fullName>ChaliceNetwork</fullName>
            </value>
            <value>
                <fullName>Clearbanc</fullName>
            </value>
            <value>
                <fullName>ClientBooks</fullName>
            </value>
            <value>
                <fullName>Community Tax</fullName>
            </value>
            <value>
                <fullName>Company.com</fullName>
            </value>
            <value>
                <fullName>Corpnet</fullName>
            </value>
            <value>
                <fullName>Corp Offer</fullName>
            </value>
            <value>
                <fullName>Coverwallet</fullName>
            </value>
            <value>
                <fullName>ZenBusiness</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Distribute_Date__c.field-meta.xml
<CustomField>
    <fullName>Distribute_Date__c</fullName>
    <formula>Account.Distribute_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Distribute Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <formula>TEXT( Account.Lead_Source__c )</formula>
    <label>Lead Source</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventLeadSourceTrackingHelperTest.cls
/**
*   Overview: Test class for EventLeadSourceTrackingHelper
*   Author: Koby Campbell
*   Date: June 2021
*/

@IsTest
private class EventLeadSourceTrackingHelperTest{
    @IsTest
    private static void testEventLeadSourceTracking() {
        EventLeadSourceTrackingHelper batchJob = new EventLeadSourceTrackingHelper(30);
        batchJob.manualExecution();

        List<Event> testEvents = new List<Event>([
            SELECT Id, WhoId, Lead_Source__c, Distribute_Date__c
            FROM Event 
            WHERE Distribute_Date__c = N_DAYS_AGO:15
            AND Lead_Source__c = 'ZenBusiness'
        ]);

        System.assertEquals(10, testEvents.size(), 'Lead Source and Distribute Date Tracking Was Not Added to all Events');

    }

    @TestSetup
    private static void testSetup() {
        Test.startTest();
        Id profileId = [SELECT Id, Name FROM Profile WHERE Name = 'Standard User' LIMIT 1].Id;

        User testUser = TestDataGenerator.createTestUser(profileId);
        insert testUser;

        List<Account> toInsertAccounts = new List<Account>();
        //Make 5 Accounts
        for(Integer i = 0; i < 5; i++) {
            Account account = TestDataGenerator.createTestAccountWithoutOwner();
            account.Lead_Source__c = 'ZenBusiness';
            toInsertAccounts.add(account);
        }
        insert toInsertAccounts;

        List<Lead> toInsertLeads = new List<Lead>();
        //Make 5 Leads
        for(Integer i = 0; i < 5; i++) {
            Lead lead = TestDataGenerator.createTestLead(testUser.Id);
            lead.LeadSource = 'ZenBusiness';
            toInsertLeads.add(lead);
        }
        insert toInsertLeads;

        List<Contact> toInsertContacts = new List<Contact>();
        //Make 5 Contacts
        for(Integer i = 0; i < 5; i++) {
            Contact contact = TestDataGenerator.createTestContact(toInsertAccounts[i]);
            contact.LeadSource = 'ZenBusiness';
            toInsertContacts.add(contact);
        }
        insert toInsertContacts;

        //Make 5 Events with Lead WhoIds
        List<Event> toInsertLEvents = new List<Event>();
        for(Integer i = 0; i < 5; i++) {
            Event event = TestDataGenerator.createTestEvent();
            event.WhoId = toInsertLeads[i].Id;
            toInsertLEvents.add(event);
        }
        insert toInsertLEvents;

        //Make 5 Events with Contact WhoIds
        List<Event> toInsertCEvents = new List<Event>();
        for(Integer i = 0; i < 5; i++) {
            Event event = TestDataGenerator.createTestEvent();
            event.WhoId = toInsertContacts[i].Id;
            toInsertCEvents.add(event);
        }
        insert toInsertCEvents;
        Test.stopTest();

    }
}