force-app/main/default/objects/Account/fields/Entity_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>Entity_Tax_Classification__c</fullName>
    <label>Entity Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>C Corporation</fullName>
            </value>
            <value>
                <fullName>S Corporation</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>DBA</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
            <value>
                <fullName>Personal Only</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead_Type_New__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type_New__c</fullName>
    <label>Lead Type New</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1800Accountant App</fullName>
            </value>
            <value>
                <fullName>1800Acct EIN</fullName>
            </value>
            <value>
                <fullName>1800Acct Homepage</fullName>
            </value>
            <value>
                <fullName>1800Acct MobileHome</fullName>
            </value>
            <value>
                <fullName>Abandoner</fullName>
            </value>
            <value>
                <fullName>Abandoner Non-Buyers</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Agent Referral</fullName>
            </value>
            <value>
                <fullName>App Download</fullName>
            </value>
            <value>
                <fullName>ASAP Lead</fullName>
            </value>
            <value>
                <fullName>Back to Business</fullName>
            </value>
            <value>
                <fullName>BAP</fullName>
            </value>
            <value>
                <fullName>BA - UA</fullName>
            </value>
            <value>
                <fullName>Blog Join Now</fullName>
            </value>
            <value>
                <fullName>Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Opt In</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Services</fullName>
            </value>
            <value>
                <fullName>BPlans Referral</fullName>
            </value>
            <value>
                <fullName>BTP</fullName>
            </value>
            <value>
                <fullName>BTP, LP, and BTOI</fullName>
            </value>
            <value>
                <fullName>BTP, LP, and STF</fullName>
            </value>
            <value>
                <fullName>BTP, LP, STF, and BTOI</fullName>
            </value>
            <value>
                <fullName>BTP and Business LP</fullName>
            </value>
            <value>
                <fullName>BTP and Buyer Tax Opt In</fullName>
            </value>
            <value>
                <fullName>BTP and STF</fullName>
            </value>
            <value>
                <fullName>BTP-Standalone</fullName>
            </value>
            <value>
                <fullName>Business Accounting</fullName>
            </value>
            <value>
                <fullName>Business LP</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Entity_Tax_Classification__c.field-meta.xml
<CustomField>
    <fullName>Entity_Tax_Classification__c</fullName>
    <label>Entity Tax Classification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sole Proprietorship</fullName>
                <label>DBA/Sole Proprietorship</label>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>C Corporation</fullName>
            </value>
            <value>
                <fullName>S Corporation</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
            <value>
                <fullName>Undetermined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Type_New__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type_New__c</fullName>
    <description>New multi-select picklist for tracking multiple lead types</description>
    <label>Lead Type New</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>1-800Accountant</fullName>
            </value>
            <value>
                <fullName>1800Accountant App</fullName>
            </value>
            <value>
                <fullName>1-800Accountant Registration</fullName>
            </value>
            <value>
                <fullName>1800Acct EIN</fullName>
            </value>
            <value>
                <fullName>1800Acct Homepage</fullName>
            </value>
            <value>
                <fullName>1800Acct MobileHome</fullName>
            </value>
            <value>
                <fullName>1800 BTP</fullName>
            </value>
            <value>
                <fullName>Abandoner</fullName>
            </value>
            <value>
                <fullName>Abandoner Non-Buyers</fullName>
            </value>
            <value>
                <fullName>Accounting</fullName>
            </value>
            <value>
                <fullName>Accounting (Business)</fullName>
            </value>
            <value>
                <fullName>Accounting Services</fullName>
            </value>
            <value>
                <fullName>Affiliate</fullName>
            </value>
            <value>
                <fullName>Agent Referral</fullName>
            </value>
            <value>
                <fullName>App Download</fullName>
            </value>
            <value>
                <fullName>April Newsletter</fullName>
            </value>
            <value>
                <fullName>ASAP Lead</fullName>
            </value>
            <value>
                <fullName>Back to Business</fullName>
            </value>
            <value>
                <fullName>banking_purposes</fullName>
            </value>
            <value>
                <fullName>BAP</fullName>
            </value>
            <value>
                <fullName>BA - UA</fullName>
            </value>
            <value>
                <fullName>Blog Join Now</fullName>
            </value>
            <value>
                <fullName>Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Opt In</fullName>
            </value>
            <value>
                <fullName>Bookkeeping Services</fullName>
            </value>
            <value>
                <fullName>BPlans Partner Page Referral</fullName>
            </value>
            <value>
                <fullName>BPlans Referral</fullName>
            </value>
            <value>
                <fullName>BTP</fullName>
            </value>
            <value>
                <fullName>BTP, Business LP</fullName>
            </value>
            <value>
                <fullName>BTP, Business LP, Buyer Tax Opt In</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
            <value>
                <fullName>Test</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StandardizeEntityBatchableTest.cls
@isTest
public with sharing class StandardizeEntityBatchableTest {
    @TestSetup
    static void makeData(){
        User u = [SELECT Id FROM User WHERE Name = 'Matthew Clark' LIMIT 1];
        List<Lead> testLeads = new List<Lead>();
        testLeads.add(new Lead(
            FirstName='Test', OwnerId = u.Id, Status='New', Lead_Type_New__c='1-800Accountant', LastName='Test', Email='test@test.com', Phone='5555555555', Company='Test',
            Entity_Tax_Classification__c='C'
        ));
        testLeads.add(new Lead(
            FirstName='Test', OwnerId = u.Id, Status='New', Lead_Type_New__c='1-800Accountant', LastName='Test', Email='test@test.com', Phone='5555555555', Company='Test',
            Entity_Tax_Classification__c='DBA'
        ));
        testLeads.add(new Lead(
            FirstName='Test', OwnerId = u.Id, Status='New', Lead_Type_New__c='1-800Accountant', LastName='Test', Email='test@test.com', Phone='5555555555', Company='Test',
            Entity_Tax_Classification__c='PLLC'
        ));
        testLeads.add(new Lead(
            FirstName='Test', OwnerId = u.Id, Status='New', Lead_Type_New__c='1-800Accountant', LastName='Test', Email='test@test.com', Phone='5555555555', Company='Test',
            Entity_Tax_Classification__c='NON'
        ));
        testLeads.add(new Lead(
            FirstName='Test', OwnerId = u.Id, Status='New', Lead_Type_New__c='1-800Accountant', LastName='Test', Email='test@test.com', Phone='5555555555', Company='Test',
            Entity_Tax_Classification__c='LP'
        ));
        testLeads.add(new Lead(
            FirstName='Test', OwnerId = u.Id, Status='New', Lead_Type_New__c='1-800Accountant', LastName='Test', Email='test@test.com', Phone='5555555555', Company='Test',
            Entity_Tax_Classification__c='S'
        ));
        testLeads.add(new Lead(
            FirstName='Test', OwnerId = u.Id, Status='New', Lead_Type_New__c='1-800Accountant', LastName='Test', Email='test@test.com', Phone='5555555555', Company='Test',
            Entity_Tax_Classification__c='NA'
        ));
        insert testLeads;


        List<Account> testAccounts = new List<Account>();
        testAccounts.add(new Account(
            Name='Test',
            Entity_Tax_Classification__c='C'
        ));
        testAccounts.add(new Account(
            Name='Test',
            Entity_Tax_Classification__c='DBA'
        ));
        testAccounts.add(new Account(
            Name='Test',
            Entity_Tax_Classification__c='PLLC'
        ));
        testAccounts.add(new Account(
            Name='Test',
            Entity_Tax_Classification__c='NON'
        ));
        testAccounts.add(new Account(
            Name='Test',
            Entity_Tax_Classification__c='LP'
        ));
        testAccounts.add(new Account(
            Name='Test',
            Entity_Tax_Classification__c='S'
        ));
        testAccounts.add(new Account(
            Name='Test',
            Entity_Tax_Classification__c='NA'
        ));
        insert testAccounts;
    }

    @isTest 
    public static void testBatch(){
        Test.startTest();
        StandardizeEntityBatchable leadBatch = new StandardizeEntityBatchable(Date.today(), 'Lead');
        Database.executeBatch(leadBatch);
        StandardizeEntityBatchable accountBatch = new StandardizeEntityBatchable(Date.today(), 'Account');
        Database.executeBatch(accountBatch);
        Test.stopTest();

        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE Entity_Tax_Classification__c = 'C Corporation']);
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE Entity_Tax_Classification__c = 'DBA/Sole Proprietorship']);
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE Entity_Tax_Classification__c = 'LLC']);
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE Entity_Tax_Classification__c = 'Partnership']);
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE Entity_Tax_Classification__c = 'Non-Profit']);
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE Entity_Tax_Classification__c = 'S Corporation']);
        System.assertEquals(1, [SELECT COUNT() FROM Lead WHERE Entity_Tax_Classification__c = 'Undetermined']);

        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Entity_Tax_Classification__c = 'C Corporation']);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Entity_Tax_Classification__c = 'DBA']);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Entity_Tax_Classification__c = 'LLC']);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Entity_Tax_Classification__c = 'Partnership']);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Entity_Tax_Classification__c = 'Non-Profit']);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Entity_Tax_Classification__c = 'S Corporation']);
        System.assertEquals(1, [SELECT COUNT() FROM Account WHERE Entity_Tax_Classification__c = 'Undetermined']);
    }
}