force-app/main/default/objects/Account/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <color>#0B6FCE</color>
                <label>New</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
                <color>#78C953</color>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>Call Back Set</fullName>
                <color>#E27001</color>
                <label>Call Back Set</label>
            </value>
            <value>
                <fullName>1-1 Request</fullName>
                <color>#66E9BD</color>
                <label>1-1 Request</label>
            </value>
            <value>
                <fullName>1-1 No Show</fullName>
                <color>#0B24BE</color>
                <label>1-1 No Show</label>
            </value>
            <value>
                <fullName>1-1 Cancelled</fullName>
                <color>#419249</color>
                <label>1-1 Cancelled</label>
            </value>
            <value>
                <fullName>Pitched</fullName>
                <color>#B6E32E</color>
                <label>Pitched</label>
            </value>
            <value>
                <fullName>Qualified</fullName>
                <color>#641CCF</color>
                <label>Qualified</label>
            </value>
            <value>
                <fullName>Attempted</fullName>
            </value>
            <value>
                <fullName>Bad Number</fullName>
                <color>#F96FB7</color>
                <label>Bad Number</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
                <color>#2F5D85</color>
                <label>Not Interested</label>
            </value>
            <value>
                <fullName>Dupe</fullName>
                <color>#AFCADF</color>
                <label>Dupe</label>
            </value>
            <value>
                <fullName>Do Not Call</fullName>
                <color>#EFAE73</color>
                <label>Do Not Call</label>
            </value>
            <value>
                <fullName>EF Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Transfer_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Eligible__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transfer Eligible?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestTransferActions.cls
@isTest
private class TestTransferActions {
	
	static testMethod void TestSetTransferEligibilityonLeads() {
		Lead l = new Lead();
		l.firstname = 'Test';
		l.lastname =  'Lead';
		l.Company = 'Test Company';
		l.Status = 'New';
		Test.startTest();
		insert l;
		TransferActions.SetTransferEligibilityonLeads();
		Lead testlead = [SELECT ID,Status,Transfer_Eligible__c FROM Lead WHERE ID = :l.id];
		System.assert(testlead.Transfer_Eligible__c == FALSE,'Lead given transfer eligibility incorrectly');
		Test.stopTest();
	}
	
	static testMethod void TestSetTransferEligibilityonAccounts() {
		Account a = new Account();
		a.name = 'Test Account';
		a.Lead_Status__c = 'New';
		Test.startTest();
		insert a;
		TransferAccts.SetTransferEligibilityonAccounts();
		Account testacct = [SELECT ID,Lead_Status__c,Transfer_Eligible__c FROM Account WHERE ID = :a.id];
		System.assert(testacct.Transfer_Eligible__c == FALSE,'Account given transfer eligibility incorrectly');
		Test.stopTest();
	}
}