force-app/main/default/objects/Account/fields/New_Value__c.field-meta.xml
<CustomField>
    <fullName>New_Value__c</fullName>
    <label>New Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Old_Value__c.field-meta.xml
<CustomField>
    <fullName>Old_Value__c</fullName>
    <label>Old Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Field_Update__c/Event_Field_Update__c.object-meta.xml
<CustomObject>
    <label>Event Field Update</label>
    <nameField>
        <displayFormat>U-{00000}</displayFormat>
        <label>Update Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Field Updates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Field_Update__c/fields/Event_History__c.field-meta.xml
<CustomField>
    <fullName>Event_History__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event History</label>
    <referenceTo>Event_History__c</referenceTo>
    <relationshipLabel>Event Field Updates</relationshipLabel>
    <relationshipName>Event_Field_Updates</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Field_Update__c/fields/Updated_Field__c.field-meta.xml
<CustomField>
    <fullName>Updated_Field__c</fullName>
    <label>Updated Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_History__c/Event_History__c.object-meta.xml
<CustomObject>
    <description>Psuedo junction object to organize Event Field Updates</description>
    <label>Event History</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/BackfillEventUpdatesBatchableTest.cls
@isTest
public without sharing class BackfillEventUpdatesBatchableTest {

    @isTest
    public static void testBatch(){
        User u = [SELECT Id FROM User WHERE Name = 'Matthew Clark' LIMIT 1];
        Account account = new Account(
            OwnerId = u.Id,
            Name = 'Test Account',
            Email_Campaign_ID__c = '12345',
            Email_Campaign_ID_Last_Touch__c = '12345'
        );
        insert account;
        
        Event_History__c history = new Event_History__c();
        insert history; 

        Event testEvent = new Event(
            OwnerId = u.Id,
            WhatId = account.Id,
            // WhoId = testContact.Id,
            Subject = 'Test Event',
            StartDateTime = System.now(),
            EndDateTime = System.now().addMinutes(30),
            Email_Campaign_ID__c = '12345',
            Type_of_Appointment__c = 'Tax Savings Analysis',
            Portal_Event_Owner__c = 'Matthew Clark',
            Event_History__c = history.Id
        );
        insert testEvent;

        Event_Field_Update__c up = new Event_Field_Update__c(
            Updated_Field__c = 'Show As',
            Old_Value__c = 'Busy',
            New_Value__c = 'Free',
            Event_History__c = history.Id
        );
        insert up;
        System.debug(testEvent);
        System.debug(up);
        Test.startTest();
        System.debug(Database.executeBatch(new BackfillEventUpdatesBatchable(null)));
        Test.stopTest();
        System.assert([SELECT COUNT() FROM Event_Field_Update__c WHERE Update_made_in_change_window__c = true] > 0);
    }
}