force-app/main/default/objects/Lead/fields/Attended_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Attended_Webinar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attended Webinar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Webinar_Request__c.field-meta.xml
<CustomField>
    <fullName>Webinar_Request__c</fullName>
    <label>Webinar Request</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TestWebinarActions.cls
@isTest
private class TestWebinarActions {
	
	static testMethod void TestSetWebinarNoShows() {
		Lead l = new Lead();
		l.firstname = 'Test';
		l.lastname =  'Lead';
		l.Company = 'Test Company';
		l.Webinar_Request__c = System.now();
		l.attended_Webinar__c = FALSE;
		l.Status = 'New';
		Test.startTest();
		insert l;
		WebinarActions.SetWebinarNoShowsAndAttends();
		Lead testlead = [SELECT ID,Status FROM Lead WHERE ID = :l.id];
		System.assert(testlead.Status == 'Webinar No Show','Lead not set to Webinar No Show');
		l.attended_Webinar__c = TRUE;
		update l;
		WebinarActions.SetWebinarNoShowsAndAttends();	
		testlead = [SELECT ID,Status FROM Lead WHERE ID = :l.id];			
		System.assert(testlead.Status == 'Webinar Attended','Lead not set to Webinar Attended');
		Test.stopTest();
	}
}