force-app/main/default/objects/Legal_Zoom__c/Legal_Zoom__c.object-meta.xml
<CustomObject>
    <label>Legal Zoom</label>
    <nameField>
        <label>Legal Zoom Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Zoom</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Zoom__c/fields/Business_Purpose__c.field-meta.xml
<CustomField>
    <fullName>Business_Purpose__c</fullName>
    <label>Business Purpose</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Date_Orders__c.field-meta.xml
<CustomField>
    <fullName>Date_Orders__c</fullName>
    <label>Date Orders</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/EMail__c.field-meta.xml
<CustomField>
    <fullName>EMail__c</fullName>
    <label>E-Mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Mailing_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Address__c</fullName>
    <label>Mailing Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <externalId>true</externalId>
    <label>Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Process__c.field-meta.xml
<CustomField>
    <fullName>Process__c</fullName>
    <label>Process</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DBA</fullName>
            </value>
            <value>
                <fullName>Incorporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Non-Profit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Sent_to_Customer__c.field-meta.xml
<CustomField>
    <fullName>Sent_to_Customer__c</fullName>
    <label>Sent to Customer</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/State_of_Formation__c.field-meta.xml
<CustomField>
    <fullName>State_of_Formation__c</fullName>
    <label>State of Formation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legal_Zoom__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestBatchProcessLegalZoom.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest (seeAllData=true)
private class TestBatchProcessLegalZoom {
/*
    static testMethod void myUnitTest() {
        Legal_Zoom__c lz = new Legal_Zoom__c();
        lz.Business_Purpose__c = 'test text';
        lz.City__c = 'Toronto';
        lz.Current_Status__c = 'Pending';
        lz.Date_Orders__c = Date.today();
        lz.Date_Started__c = Date.today();
        lz.Email__c = 'abc@abc.abc1234';
        lz.First_Name__c = 'test';
        lz.Last_Name__c = 'tester1';
        lz.Mailing_Address__c = '133 fake st';
        lz.Number__c = '12345123451';
        lz.Order_Number__c = '12345123';
        lz.Package__c = 'test';
        lz.Phone__c = '12123415';
        lz.Postal_Code__c = '01521';
        lz.Process__c = 'Incorporation';
        lz.Product_Name__c = '1234';
        lz.Sent_To_Customer__c = Date.today();
        lz.State__c = 'AZ';
        lz.State_Of_Formation__c = '123';
        lz.Status__c = 'Pending';
        
        insert lz;
        
        Test.startTest();
        BatchProcessLegalZoom b = new BatchProcessLegalZoom();
        Database.executeBatch(b);
        Test.stopTest();
    }*/
}