force-app/main/default/objects/Accounting_Process__c/Accounting_Process__c.object-meta.xml
<CustomObject>
    <label>Accounting Process</label>
    <nameField>
        <label>Accounting Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounting Processes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accounting_Process__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounting Processes</relationshipLabel>
    <relationshipName>Accounting_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accounting_Process__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounting Processes</relationshipLabel>
    <relationshipName>Accounting_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accounting_Process__c/fields/Personal__c.field-meta.xml
<CustomField>
    <fullName>Personal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Personal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Accounting_Process__c/fields/Tax_Prep_Status__c.field-meta.xml
<CustomField>
    <fullName>Tax_Prep_Status__c</fullName>
    <label>Tax Prep Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Prep Comp Review</fullName>
            </value>
            <value>
                <fullName>Awaiting Auto-Flow</fullName>
            </value>
            <value>
                <fullName>Auto-Flowed Missing Documents</fullName>
            </value>
            <value>
                <fullName>Preparation</fullName>
            </value>
            <value>
                <fullName>Preparation - Data Entered</fullName>
            </value>
            <value>
                <fullName>Additional info Request Sent</fullName>
            </value>
            <value>
                <fullName>Additional info Request Sent - No Notification</fullName>
            </value>
            <value>
                <fullName>Additional Info Received</fullName>
            </value>
            <value>
                <fullName>Awaiting Internal Bookkeeping</fullName>
            </value>
            <value>
                <fullName>Review</fullName>
            </value>
            <value>
                <fullName>Review - No Client Notification</fullName>
            </value>
            <value>
                <fullName>Review - Owes</fullName>
            </value>
            <value>
                <fullName>Review- In Progress</fullName>
            </value>
            <value>
                <fullName>Corrections Needed</fullName>
            </value>
            <value>
                <fullName>Corrections Addressed</fullName>
            </value>
            <value>
                <fullName>To Be Posted</fullName>
            </value>
            <value>
                <fullName>To Be Posted - Owes</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Approval</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Approval - Owes</fullName>
            </value>
            <value>
                <fullName>Awaiting Client Approval - No Notification</fullName>
            </value>
            <value>
                <fullName>Internal Completed - Govt forms unavailable</fullName>
            </value>
            <value>
                <fullName>E-Filed Awaiting Govt. Acceptance</fullName>
            </value>
            <value>
                <fullName>Rejections</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed - Paper Filed</fullName>
            </value>
            <value>
                <fullName>E-File Complete - State Paper Filed</fullName>
            </value>
            <value>
                <fullName>Extension Filed - Awaiting Client Info</fullName>
            </value>
            <value>
                <fullName>Long-Term Pending</fullName>
            </value>
            <value>
                <fullName>Discard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business__c/Business__c.object-meta.xml
<CustomObject>
    <label>Business</label>
    <nameField>
        <label>Businesss Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Business__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Businesses</relationshipLabel>
    <relationshipName>Businesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Businesses</relationshipLabel>
    <relationshipName>Businesses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Contact)</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Trigger_Setting__mdt/Event_Trigger_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata will be used to Enable/Disable the execution code blocks of Event Trigger.</description>
    <label>Event Trigger Setting</label>
    <pluralLabel>Event Trigger Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Trigger_Setting__mdt/fields/Disable_Tax_Season_SMS_Scheduling__c.field-meta.xml
<CustomField>
    <fullName>Disable_Tax_Season_SMS_Scheduling__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True(Checked) : SMS Scheduler records will not be created for Tax Season (Accounting Process object). 
False(Unchecked) : SMS Scheduler records will be created for Tax Season (Accounting Process object).</description>
    <label>Disable Tax Season SMS Scheduling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tax_Filing_Deadline__mdt/Tax_Filing_Deadline__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata type will store tax filing deadline for both Person &amp; Business.</description>
    <label>Tax Filing Deadline</label>
    <pluralLabel>Tax Filing Deadline</pluralLabel>
</CustomObject>

force-app/main/default/objects/Tax_Filing_Deadline__mdt/fields/Business_Tax_Filing_Deadline_SMS_Date__c.field-meta.xml
<CustomField>
    <fullName>Business_Tax_Filing_Deadline_SMS_Date__c</fullName>
    <description>Last Friday before Business Tax Filing Deadline</description>
    <label>Business Tax Filing Deadline SMS Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tax_Filing_Deadline__mdt/fields/Business_Tax_Message__c.field-meta.xml
<CustomField>
    <fullName>Business_Tax_Message__c</fullName>
    <label>Business Tax Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tax_Filing_Deadline__mdt/fields/Personal_Tax_Filing_Deadline_SMS_Date__c.field-meta.xml
<CustomField>
    <fullName>Personal_Tax_Filing_Deadline_SMS_Date__c</fullName>
    <description>Last Friday before Personal Tax Filing Deadline</description>
    <label>Personal Tax Filing Deadline SMS Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Tax_Filing_Deadline__mdt/fields/Personal_Text_Message__c.field-meta.xml
<CustomField>
    <fullName>Personal_Text_Message__c</fullName>
    <label>Personal Text Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_SMS_For_Tax_Season.cls
//Deprecated
global class Batch_SMS_For_Tax_Season implements Database.Batchable<sObject> { //
    
    String query;
    
    global Batch_SMS_For_Tax_Season() {
        
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        query = 'Select Id, CreatedDate, Tax_Prep_Status__c, Account__c, Contact__c, Contact__r.Phone, Contact__r.Name, Name, Business__c, Personal__c from Accounting_Process__c where Tax_Prep_Status__c in (\'Additional info Request Sent\', \'Additional info Request Sent - No Notification\', \'Awaiting Client Approval\', \'Awaiting Client Approval - Owes\', \'Awaiting Client Approval - No Notification\')';
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {

    //     List<Event_Trigger_Setting__mdt> eventSettingCustomMetadata = [SELECT Disable_Tax_Season_SMS_Scheduling__c FROM Event_Trigger_Setting__mdt 
    //                                                                     WHERE DeveloperName='Disable_SMS_Scheduling' ] ;

    //     List<Tax_Filing_Deadline__mdt> lstTaxFiling = [select id, Business_Tax_Filing_Deadline_SMS_Date__c, Business_Tax_Message__c, Personal_Tax_Filing_Deadline_SMS_Date__c, Personal_Text_Message__c 
    //                                                     from Tax_Filing_Deadline__mdt where developername='Tax_Filing_Deadline'];

    //     if(eventSettingCustomMetadata.size() > 0){
    //         if(eventSettingCustomMetadata[0].Disable_Tax_Season_SMS_Scheduling__c == true)
    //             return;
    //     }else{
    //         return;
    //     }

    //     List<Accounting_Process__c> lstAddtnlInfo = new List<Accounting_Process__c>();
    //     List<Accounting_Process__c> lstAwtngApprvl = new List<Accounting_Process__c>();
    //     List<Accounting_Process__c> lstPersonal = new List<Accounting_Process__c>();
    //     List<Accounting_Process__c> lstBusiness = new List<Accounting_Process__c>();

    //     for(SObject s : scope){

    //         Accounting_Process__c acctProcess = (Accounting_Process__c) s;

    //         if(acctProcess.Tax_Prep_Status__c == 'Additional info Request Sent' || acctProcess.Tax_Prep_Status__c == 'Additional info Request Sent - No Notification'){
    //             lstAddtnlInfo.add(acctProcess);
    //         } else if(acctProcess.Tax_Prep_Status__c == 'Awaiting Client Approval' || acctProcess.Tax_Prep_Status__c == 'Awaiting Client Approval - Owes' || acctProcess.Tax_Prep_Status__c == 'Awaiting Client Approval - No Notification'){
    //             lstAwtngApprvl.add(acctProcess);
    //         }

    //         if(acctProcess.Business__c){    //It's for Business
    //             lstBusiness.add(acctProcess);
    //         }

    //         if(acctProcess.Personal__c){    //It's for Personal
    //             lstPersonal.add(acctProcess);
    //         }
    //     }

    //     //if(lstAddtnlInfo.size() > 0)
    //     //    SMS_For_Tax_Season_Helper.createScheduleMsgForAddtnlInfo(lstAddtnlInfo);

    //     //if(lstAwtngApprvl.size() > 0)
    //     //    SMS_For_Tax_Season_Helper.createScheduleMsgForAwaitingApprvl(lstAwtngApprvl);
        
    //     //if(lstPersonal.size() > 0 && lstTaxFiling.size() > 0)
    //     //    SMS_For_Tax_Season_Helper.createScheduleMsgForPersonal(lstPersonal, lstTaxFiling[0]);

    //     //if(lstBusiness.size() > 0 && lstTaxFiling.size() > 0)
    //     //    SMS_For_Tax_Season_Helper.createScheduleMsgForBusiness(lstBusiness, lstTaxFiling[0]);

    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
}